### ISSUE TITLE
Explain why USB>TTL Flashing works different than writing an MTD device?

### ISSUE THREAD

**Issue by mystica555** [Chadster766/McDebian#1]
The comment says it all.

Unless there are some weird checks and balances that either openwrt and/or stock firmware use, what difference is there in using dd, to shove some bytes, into an MTD or ubi device, that using uboot to do the same thing does differently?

**Comment by Chadster766** [comment]
Using dd or mtd-utils to write a firmware to a MTD partitions will do the same thing.

If Debian decided to rename interfaces for whatever reason during first boot without the USB to TTL cable you would have no access to the router.

DD-WRT, OpenWRT and Stock firmwares have many customizations, checks and balances during first boot to make sure they work with specific a WRT hardware versions.

**Comment by mystica555** [comment]
Understood! so it is not a logical difference, only one of "if something changes, have the console access to fix it else have a nice blue and black paperweight til you do".  Thanks!
