### ISSUE TITLE
SNORT installation script, prebuilt deb files and base configuration

### ISSUE THREAD

**Issue by Chadster766** [Chadster766/McDebian#13]
It would be great if we could test SNORT with McDebian to see if it runs well on the WRT1x00AC\S hardware platforms.

If the hardware can support it. Then we could package a tar file with the required package components prebuilt, a McDebian SNORT base configuration and an installation script to get it fired up.

**Comment by ValCher1961** [comment]
Resources will be enough?

**Comment by Chadster766** [comment]
We won't know until someone gives it a shot because I can't find any minimum hardware requirements for SNORT IDS/IPS.

**Comment by Chadster766** [comment]
Installation video
https://www.youtube.com/watch?v=GVvS8Peb2fY

**Comment by ValCher1961** [comment]
Thanks for the info, I will try this weekend.

**Comment by Chadster766** [comment]
Ok Great :smiley:

**Comment by ValCher1961** [comment]
@Chadster766
My head was spinning.
Installed snort as described -http://wiki.aanval.com/wiki/Community:Snort_2.9.2.3_Installation_Guide_for_Ubuntu_12.04,_with_Barnyard2,_Pulledpork,_and_Aanval
How came to installation rules, it became clear that the architecture they are not armfh, but in Debian repositories have packages "fwsnort" and "snort-rules".
Information on my tongue a little. These packages are compatible with snort?

**Comment by Chadster766** [comment]
Thanks for trying. I will see if I can get SNORT and Aanval installation process working for evaluation.

Also thanks for the link it bring into play the Aanval software which looks awesome :smile:

**Comment by ValCher1961** [comment]
@Chadster777
Have you tried to install suricate? The package is in the Debian repository.

**Comment by Chadster766** [comment]
I have snort running but there is a large learning curve.

Looking into Suricata as a possible alternative now.

**Comment by ValCher1961** [comment]
@Chadster766 
How's your CPU usage and network performance using snort? You tested suricata?
I am now testing suricata. In suricata has two modes IPS: NFQ and AF_PACKET.
When using IPS-NFQ greatly decreases network bandwidth, about 4-5 times. If you use the IPS-AF_PACKET speed is reduced by ~30-40%.
Here are the results:
```
Ethernet Down/Up (no IPS) -			~93/93Mbps
Ethernet Down/Up (IPS-NFQ) -		~21/20Mbps
Ethernet Down/Up (IPS-AF_PACKET) - 	~55/72Mbps
```
IPS-NFQ
```
Tasks:  77 total,   1 running,  76 sleeping,   0 stopped,   0 zombie
%Cpu0  : 34,5 us, 19,7 sy,  0,0 ni, 11,5 id,  0,0 wa,  0,0 hi, 34,2 si,  0,0 st
%Cpu1  : 62,8 us, 17,1 sy,  0,0 ni, 18,1 id,  0,0 wa,  0,0 hi,  2,0 si,  0,0 st
KiB Mem:    250732 total,   219240 used,    31492 free,     9960 buffers
KiB Swap:   524284 total,   247824 used,   276460 free.    19148 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 4009 root      20   0  453608 149028   3248 S 168,8 59,4   4:27.15 Suricata-Main
```
IPS-AF_PACKET
```
Tasks:  75 total,   1 running,  74 sleeping,   0 stopped,   0 zombie
%Cpu0  :  1,7 us,  1,7 sy,  0,0 ni, 47,7 id,  1,3 wa,  0,0 hi, 47,7 si,  0,0 st
%Cpu1  :  3,0 us,  1,0 sy,  0,0 ni, 94,0 id,  2,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem:    250732 total,   229076 used,    21656 free,    29536 buffers
KiB Swap:   524284 total,   245980 used,   278304 free.    20888 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 4009 root      20   0  453608 136992    532 S   6,3 54,6   3:28.16 Suricata-Main
```

**Comment by Chadster766** [comment]
I was planning to do some snort studying tonight. I can't post throughput comparisons yet because I need to learn more about how it operates.

Thanks for posting your results so far with Suricata.

**Comment by ValCher1961** [comment]
I never installed snort to working condition, it seemed difficult, but the suricata is easier to set up, and on their website are good explanations.

Will look forward to your results.

**Comment by ValCher1961** [comment]
I graduated from experiments with Suricata. My opinion on the use Suricata wrt1900ac (v1) is not desirable because of the small amount of RAM. Creating a swap disk is somewhat easier to work, but creates a very heavy load on the SSD. In my case Suricata used up in the peaks over 500mb main and virtual memory.

**Comment by Chadster766** [comment]
Thanks for the information and testing results.

I'm still learning and testing Snort. In snort you can configure everything. You are right a swap file is required for snort to work as well but configured for 9999tcp/udp max seems to be ok.

**Comment by ValCher1961** [comment]
Very pity that wrt1900ac (v1) is set to 256 MB memory, I think it's (v2) wrt1900ac or wrt1900acs with 512 MB would be more suitable for these purposes. By the way, the processor adequately cope with challenges.

**Comment by Chadster766** [comment]
With snort it starts out maxing the cpu's but then it seems to balance out to 50% each cpu. I don't know if that has to do with irqbalance (installed in McDebian by default) or not.

**Comment by ValCher1961** [comment]
The Suricata is very flexible, you can use the processor cores, separating threads on processor core.

**Comment by ValCher1961** [comment]
With your permission, a bit out of topic ... thoughts in hearing.

I was very upset little DRAM size wrt1900ac (v1). I haven't decided yet, but I have a desire to replace memory chips.

The original device uses a common chip Hynix H5TQ1G63BFR-PBC (64x16) it can be replaced by H5TQ2G63BFR (128x16), that amount would give 512 MB. There are more advanced chip-Hynix H5TQ1G63AFR (256x16) that can datt′ 1 GB. I understand what risks may lie in wait for me, that's still hesitate such an operation.

**Comment by Chadster766** [comment]
Interesting, are those mem chips removable? Another option would be to connect an external drive with a spinning disk for the rootfs and then create a swap file of 256MB. The performance increase might be similar.

**Comment by ValCher1961** [comment]
Memory chip need to solder. So now me and stops, although I have experience, but the risk is great.
I have installed SSD and configured swap, but no swap can not compare performance with RAM.

**Comment by jbsky** [comment]
@ValCher1961, chip need a special soldering for SMD. Socket BGA.... :cry:

**Comment by ValCher1961** [comment]
@jbsky 
Yes, I this BGA chip, air must be used for soldering soldering station with strict control of temperature and time. In my work there is this station.
At the beginning I will try modernize old NAS, he has the same chip BGA, and if all goes well, the upgraded router.

**Comment by ValCher1961** [comment]
Today tried to boost DDR3 memory up to 1 GB, but failed. It seems to me that the Board was not bred to track addresses the A14 and A15 or they do not have ballast resistors.
Hope remained the ability to increase memory up to 512 MB.
While the restored old memory.
By the way, on the Board I found two undiluted SATA ports.

**Comment by Chadster766** [comment]
Wow you are brave to try.

I never saw the sata ports you mention. Where are they located?

**Comment by ValCher1961** [comment]
Ports are under USB indicators.
![img_0933](https://cloud.githubusercontent.com/assets/17226948/19023684/f02fec30-88fc-11e6-91c4-440a8c99ef33.JPG)

**Comment by ValCher1961** [comment]
I jumped the gun a bit by restoring the old chips, one had to ring the address bus, but prozvonû when new memory chip will come from China.
Soldering chips did not cause much difficulty.

**Comment by Chadster766** [comment]
Snort will take up too many system resources and will be too complex for even a knowledgeable user.

**Comment by flyoffthehandle** [comment]
Was suricata tested? I wouldn’t mind trying if not. There is a “hybrid” (best way I know to put it) IDS I used very briefly on some other embedded boards that I know will run on this router. The only problem is that I can’t speak to if it actually provides a trustworthy level of security. It is called FalconGate. Running suricata On the router with a swap as first disk partition (HDD). Using port mirroring or a tap to pass all traffic to the monitor interface instead of inline was how I thought I’d start. If you know this works poorly I will see what falcongate can handle or try using a SSD for swap space and root with somewhat conservative settings for log archiving/deletion.

**Comment by Chadster766** [comment]
I did a little testing with snort but it was too processor\memory intensive IMO.

I haven't tried any other IDS\IPS softwares.

**Comment by ValCher1961** [comment]
Suricata on WRT1900AC v1 heavily loaded memory and a swap drive, also falling the WAN speed. I haven't tried wrt3200.

**Comment by Chadster766** [comment]
If possible it would be best to have a IPS\IDS that runs well across all WRT models.

**Comment by ValCher1961** [comment]
What are the alternatives to snort and suricana?

**Comment by flyoffthehandle** [comment]
Bro
