### ISSUE TITLE
[Discussion] Reset Button implementation

### ISSUE THREAD

**Issue by Chadster766** [Chadster766/McDebian#15]
The Reset Button seems to be operational in the kernel but is unused.

If we had a save config script that writes the /etc directory or a tar of it to the nand rootfs partitions or the USB Drive, then we might be able to use the Reset Button to pull that saved /etc snapshot to recover the router quickly. 

The use case would be user error where they lock themselves out of the Debian system with a bad configuration.  Normally you would have to use the USB to TTL cable to reverse the problem.

It's easy to make a mistake in iptables or /etc/interfaces configs.

**Comment by jbsky** [comment]
Check please if you want a gpio_keys event control.
https://github.com/jbsky/McDebian/commit/cdb6478a1bf432a91bf23b7f8bb2c2731aa6aa22

**Comment by Chadster766** [comment]
Cool thanks

**Comment by jbsky** [comment]
You need CONFIG_LEDS_TLC591XX in your .config to complete /sys/class/led/.

**Comment by ferranti** [comment]
Can't the user also simply load the USB drive on another Linux system and revert their changes to configuration files that way?

**Comment by Chadster766** [comment]
Good point 😃 

https://github.com/Chadster766/McDebian/wiki/8.-Backup-Root-File-System
