### ISSUE TITLE
SATA port multiplier is not working

### ISSUE THREAD

**Issue by edwardwong80** [Chadster766/McDebian#17]
Hi,

After installing the 4.4.16 on my WRT1900AC v2, I plugged in my Orico 3529RUS3 3-bay USB3/eSATA enclosure to the eSATA interface, the system is able to see some new drives installed to the enclosure but not usable, everytime I do mount/mkfs/other disk related command, the drives in enclosure looks like restarting, looking into dmesg log I found the following:

**[ 2676.401672] ata2: hard resetting link
[ 2676.951670] ata2: SATA link up 3.0 Gbps (SStatus 123 SControl 300)
[ 2676.958220] ata2.15: Port Multiplier 1.2, 0x197b:0x0325 r0, 5 ports, feat 0x5/0xf
[ 2676.965765] ahci-mvebu f10a8000.sata: FBS is enabled
[ 2676.971057] ata2.01: limiting SATA link speed to 1.5 Gbps
[ 2676.976537] ata2.02: limiting SATA link speed to 1.5 Gbps
[ 2676.982023] ata2.03: limiting SATA link speed to 1.5 Gbps
[ 2676.987491] ata2.04: limiting SATA link speed to 1.5 Gbps
[ 2676.992932] ata2.00: hard resetting link
[ 2677.342154] ata2.00: SATA link up 3.0 Gbps (SStatus 123 SControl 320)
[ 2677.348673] ata2.01: hard resetting link
[ 2678.421709] ata2.01: failed to resume link (SControl 0)
[ 2678.427295] ata2.01: SATA link down (SStatus 0 SControl 0)
[ 2678.432916] ata2.02: hard resetting link
[ 2679.501711] ata2.02: failed to resume link (SControl 0)
[ 2679.507311] ata2.02: SATA link down (SStatus 0 SControl 0)
[ 2679.512957] ata2.03: hard resetting link
[ 2680.581735] ata2.03: failed to resume link (SControl 0)
[ 2680.587320] ata2.03: SATA link down (SStatus 0 SControl 0)
[ 2680.593126] ata2.04: hard resetting link
[ 2681.661710] ata2.04: failed to resume link (SControl 0)
[ 2681.667297] ata2.04: SATA link down (SStatus 0 SControl 0)
[ 2681.673585] ata2.00: ATA-7: Hitachi HUAxxxxxxx, 0958, max UDMA/133
[ 2681.680231] ata2.00: 1953525168 sectors, multi 1: LBA48
[ 2681.686315] ata2.00: configured for UDMA/133
[ 2681.690722] ata2: EH complete
[ 2681.693962] ata2.00: detaching (SCSI 1:0:0:0)
[ 2681.704080] sd 1:0:0:0: [sdb] Stopping disk
[ 2683.880571] ata2.15: PMP product ID mismatch
[ 2683.884883] ata2.15: hard resetting link
[ 2684.431672] ata2.15: SATA link up 3.0 Gbps (SStatus 123 SControl 300)
[ 2684.438451] ata2.15: Port Multiplier vendor mismatch '0x197b' != '0x0'
[ 2684.445021] ata2.15: PMP revalidation failed (errno=-19)
[ 2684.450358] ata2.15: limiting SATA link speed to 1.5 Gbps
[ 2689.431669] ata2.15: hard resetting link
[ 2689.981671] ata2.15: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
[ 2689.988464] ata2.15: Port Multiplier vendor mismatch '0x197b' != '0x0'
[ 2689.995034] ata2.15: PMP revalidation failed (errno=-19)
[ 2694.981671] ata2.15: hard resetting link
[ 2695.531670] ata2.15: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
[ 2695.538452] ata2.15: Port Multiplier vendor mismatch '0x197b' != '0x0'
[ 2695.545020] ata2.15: PMP revalidation failed (errno=-19)
[ 2695.550366] ata2.15: failed to recover PMP after 5 tries, giving up
[ 2695.556667] ata2.15: Port Multiplier detaching
[ 2695.561129] ata2.00: disabled
[ 2695.564116] ata2.00: disabled**

The chipset inside is JMicron JMB321, which is a SATA II compatible chipset, and so this should support SATA 3.0Gbps but not just 1.5Gbps.

I can assure this is not hardware issue because it works fine when I use Linksys stock firmware.

**Comment by Chadster766** [comment]
I will have to research this a bit. I found the below link where a kernel patch was applied to get this to work but the post is from Jan 2015.

http://www.spinics.net/lists/linux-ide/msg49991.html

There could be a kernel hardware driver for this Orico 3529RUS3 or the eSata controller that isn't enabled or needs to be loaded via /etc/modules

Did you try boot the router with the rootfs USB Drive in the router's USB2 port and after boot plugging in the Orico 3529RUS3  into the USB3 port for testing purposes?

**Comment by Chadster766** [comment]
I'm hunting down an esata drive for testing :smile:

**Comment by Chadster766** [comment]
I should have esata drive and cable for testing tomorrow.

**Comment by Chadster766** [comment]
Ok I'm setup to troubleshoot this over the weekend :smile:

**Comment by edwardwong80** [comment]
Is yours a multi-bay eSATA enclosure or just a single drive? I think they behave differently.
I am planning to put the 4.4.18 for testing first (USB should be no issue as there is USB<>SATA layer in between and kernel driver in use will be different)

The reason why I would like this to work is because of [another GitHub project](https://github.com/openmediavault/openmediavault), it's based on Debian Linux and this can turn the router into NAS!

**Comment by edwardwong80** [comment]
FYI I've used the same HDD enclosure on a Debian Wheezy (AMD64) and it works fine as well, so I guess it might be some driver were missing during kernel compilation?

**Comment by Chadster766** [comment]
That could be. 

At least when I test with my esata drive we will have something to compare against for troubleshooting purposes.

**Comment by edwardwong80** [comment]
Last night I tried to upgrade to 4.4.18, situation didn't improve, now I don't even need to touch those drives, the SATA link will simply reset periodically, error messages are same.

**Comment by Chadster766** [comment]
It looks like my esata drive connected at 3.0 Gbps bit I don't get that 

Dec 31 18:00:13 MCDEBIAN kernel: ata1: link is slow to respond, please be patient (ready=0)
Dec 31 18:00:13 MCDEBIAN kernel: ata1: SATA link up 3.0 Gbps (SStatus 123 SControl F300)
Dec 31 18:00:13 MCDEBIAN kernel: ata1.15: Port Multiplier 1.2, 0x197b:0x0325 r0, 5 ports, feat 0x5/0xf
Dec 31 18:00:13 MCDEBIAN kernel: ata1.00: hard resetting link
Dec 31 18:00:13 MCDEBIAN kernel: ata1.01: hard resetting link
Dec 31 18:00:13 MCDEBIAN kernel: ata1.01: failed to resume link (SControl 0)
Dec 31 18:00:13 MCDEBIAN kernel: ata1.02: hard resetting link
Dec 31 18:00:13 MCDEBIAN kernel: ata1.02: failed to resume link (SControl 0)
Dec 31 18:00:13 MCDEBIAN kernel: ata1.03: hard resetting link
Dec 31 18:00:13 MCDEBIAN kernel: ata1.03: failed to resume link (SControl 0)
Dec 31 18:00:13 MCDEBIAN kernel: ata1.04: hard resetting link
Dec 31 18:00:13 MCDEBIAN kernel: ata1.04: failed to resume link (SControl 0)
Dec 31 18:00:13 MCDEBIAN kernel: ata1.00: ATA-7: G-DRIVE, 0960, max UDMA/133
Dec 31 18:00:13 MCDEBIAN kernel: ata1.00: 5860533168 sectors, multi 1: LBA48
Dec 31 18:00:13 MCDEBIAN kernel: ata1.00: configured for UDMA/133
Dec 31 18:00:13 MCDEBIAN kernel: ata1: EH complete
Dec 31 18:00:13 MCDEBIAN kernel: scsi 0:0:0:0: Direct-Access     ATA      G-DRIVE          0960 PQ: 0 ANSI: 5
Dec 31 18:00:13 MCDEBIAN kernel: sd 0:0:0:0: [sdb] 5860533168 512-byte logical blocks: (3.00 TB/2.73 TiB)
Dec 31 18:00:13 MCDEBIAN kernel: sd 0:0:0:0: [sdb] Write Protect is off
Dec 31 18:00:13 MCDEBIAN kernel: sd 0:0:0:0: [sdb] Mode Sense: 00 3a 00 00
Dec 31 18:00:13 MCDEBIAN kernel: sd 0:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Dec 31 18:00:13 MCDEBIAN kernel:  sdb: sdb1 sdb2
Dec 31 18:00:13 MCDEBIAN kernel: sd 0:0:0:0: [sdb] Attached SCSI disk

I compiled the FUSE driver to read\write to the ntfs formatted partition because I needed to keep the existing files. My test showed little difference when the drive was connected esata or USB3.0.

**Comment by edwardwong80** [comment]
I saw those "hard resetting link" kernel message, so is yours working properly?

**Comment by Chadster766** [comment]
Seems to be. I'm running the below drive stress test to see if it disconnects over time:

#!/bin/bash


until [ 0 = 1 ]; do
        logger "Test Drive running dd....."
        dd if=/dev/zero of=/mnt/ext-drive/test/testfile bs=1M count=1024
        #echo "testing......"
        sleep 30
done

**Comment by Chadster766** [comment]
The test script ran dd 1GB file creation 302 time today and the esata drive never disconnect.

McDebian 4.4.18 (beta)

**Comment by Chadster766** [comment]
Try the new McDebian 4.7.5 Beta. Maybe the new kernel drivers better support your device.

#18

**Comment by edwardwong80** [comment]
Just tested with 4.7.5, same behaviour, but I found the following link about Banana Pi (also ARM platform) with eSATA kernel modification, not sure if we can follow it the same way, so where can I get the kernel source for McDebian?

**Comment by Chadster766** [comment]
The current Linux build config is in the McDebian GitHub repo but I recommend I build you a firmware and give you a download link with the change you propose. If it works for you it is probably required for others too.

**Comment by Chadster766** [comment]
Try this test firmware for the WRT1900AC V2:
```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V2-FW_VER1_kernel_4_7_5-esata-test.img
```
Kernel config builds the fuse driver into the kernel:
```
root@McDev1:~/McDebian/kernel/linux-4.7.5# git diff .config
diff --git a/.config b/.config
index 76b365c..94b7db5 100644
--- a/.config
+++ b/.config
@@ -3513,7 +3513,8 @@ CONFIG_INOTIFY_USER=y
 # CONFIG_QUOTA is not set
 # CONFIG_QUOTACTL is not set
 CONFIG_AUTOFS4_FS=y
-# CONFIG_FUSE_FS is not set
+CONFIG_FUSE_FS=y
+# CONFIG_CUSE is not set
 # CONFIG_OVERLAY_FS is not set

 #
```
Change made to the ahci.c code:
```
root@McDev1:~/McDebian/kernel/linux-4.7.5# git diff drivers/ata/ahci.c
diff --git a/drivers/ata/ahci.c b/drivers/ata/ahci.c
index a83bbcc..0477967 100644
--- a/drivers/ata/ahci.c
+++ b/drivers/ata/ahci.c
@@ -196,7 +196,7 @@ static const struct ata_port_info ahci_port_info[] = {
        },
        [board_ahci_mv] = {
                AHCI_HFLAGS     (AHCI_HFLAG_NO_NCQ | AHCI_HFLAG_NO_MSI |
-                                AHCI_HFLAG_MV_PATA | AHCI_HFLAG_NO_PMP),
+                                AHCI_HFLAG_MV_PATA),
                .flags          = ATA_FLAG_SATA | ATA_FLAG_PIO_DMA,
                .pio_mask       = ATA_PIO4,
                .udma_mask      = ATA_UDMA6,
```

**Comment by Chadster766** [comment]
Testing:
```
root@MCDEBIAN:/mnt/esata/test# journalctl|grep ata
Dec 31 18:00:09 MCDEBIAN kernel: ahci-mvebu f10a8000.sata: AHCI 0001.0000 32 slots 2 ports 6 Gbps 0x3 impl platform mode
Dec 31 18:00:09 MCDEBIAN kernel: ahci-mvebu f10a8000.sata: flags: 64bit ncq sntf led only pmp fbs pio slum part sxs
Dec 31 18:00:09 MCDEBIAN kernel: ata1: SATA max UDMA/133 mmio [mem 0xf10a8000-0xf10a9fff] port 0x100 irq 41
Dec 31 18:00:09 MCDEBIAN kernel: ata2: SATA max UDMA/133 mmio [mem 0xf10a8000-0xf10a9fff] port 0x180 irq 41
Dec 31 18:00:09 MCDEBIAN kernel: ata1: SATA link down (SStatus 0 SControl 300)
Dec 31 18:00:09 MCDEBIAN kernel: ata2: SATA link up 3.0 Gbps (SStatus 123 SControl 300)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.15: Port Multiplier 1.2, 0x197b:0x0325 r0, 5 ports, feat 0x5/0xf
Dec 31 18:00:09 MCDEBIAN kernel: ahci-mvebu f10a8000.sata: FBS is enabled
Dec 31 18:00:09 MCDEBIAN kernel: ata2.00: hard resetting link
Dec 31 18:00:09 MCDEBIAN kernel: ata2.00: SATA link up 3.0 Gbps (SStatus 123 SControl 320)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.01: hard resetting link
Dec 31 18:00:09 MCDEBIAN kernel: ata2.01: failed to resume link (SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.01: SATA link down (SStatus 0 SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.02: hard resetting link
Dec 31 18:00:09 MCDEBIAN kernel: ata2.02: failed to resume link (SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.02: SATA link down (SStatus 0 SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.03: hard resetting link
Dec 31 18:00:09 MCDEBIAN kernel: ata2.03: failed to resume link (SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.03: SATA link down (SStatus 0 SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.04: hard resetting link
Dec 31 18:00:09 MCDEBIAN kernel: ata2.04: failed to resume link (SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.04: SATA link down (SStatus 0 SControl 0)
Dec 31 18:00:09 MCDEBIAN kernel: ata2.00: ATA-7: G-DRIVE, 0960, max UDMA/133
Dec 31 18:00:09 MCDEBIAN kernel: ata2.00: 5860533168 sectors, multi 1: LBA48
Dec 31 18:00:09 MCDEBIAN kernel: ata2.00: configured for UDMA/133
Dec 31 18:00:09 MCDEBIAN kernel: ata2: EH complete
Dec 31 18:00:09 MCDEBIAN kernel: EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
root@MCDEBIAN:/mnt/esata/test# dd if=/dev/zero of=/mnt/esata/testfile bs=1G count=1 oflag=direct
dd: memory exhausted by input buffer of size 1073741824 bytes (1.0 GiB)
root@MCDEBIAN:/mnt/esata/test# dd if=/dev/zero of=/mnt/esata/testfile bs=1G count=1
dd: memory exhausted by input buffer of size 1073741824 bytes (1.0 GiB)
root@MCDEBIAN:/mnt/esata/test# dd if=/dev/zero of=/mnt/esata/testfile bs=1MB count=1000 oflag=direct
1000+0 records in
1000+0 records out
1000000000 bytes (1.0 GB) copied, 6.76347 s, 148 MB/s
```

**Comment by Chadster766** [comment]
Do you still get the same error with this test firmware?

**Comment by edwardwong80** [comment]
Same error, nothing changed, very weird.

**Comment by Chadster766** [comment]
This is the specific error you are concerned about:
`Port Multiplier vendor mismatch '0x197b' != '0x0'`

**Comment by ValCher1961** [comment]
@Chadster766 
Sorry, but it seems to me in the diff you do not have to add
`+                                AHCI_HFLAG_MV_PATA),`
or am I wrong...

**Comment by Chadster766** [comment]
```
-                                AHCI_HFLAG_MV_PATA | AHCI_HFLAG_NO_PMP),
+                                AHCI_HFLAG_MV_PATA),
```
Means that "AHCI_HFLAG_MV_PATA | AHCI_HFLAG_NO_PMP)," is remove and replaced with "AHCI_HFLAG_MV_PATA),".

Effectively removing AHCI_HFLAG_NO_PMP.

If that is what you are asking.

**Comment by ValCher1961** [comment]
Delete entire line
`-                                AHCI_HFLAG_MV_PATA | AHCI_HFLAG_NO_PMP),`
and add
`+       ),`

**Comment by Chadster766** [comment]
Ah, lets give that a shot.

**Comment by ValCher1961** [comment]
Still, you should check.

**Comment by Chadster766** [comment]
I've done a lot of research on this issue and esata device. It looks like support was broken for the JMB394 chipset in 2014 with Linux 3.10.33 release and the commit below:

```
commit 69f554c94a4e0dce7d933358dec416b74b6424a6
Author: Denis V. Lunev <den@openvz.org>
Date:   Thu Jan 30 15:20:30 2014 +0400

    ata: enable quirk from jmicron JMB350 for JMB394
    
    commit efb9e0f4f43780f0ae0c6428d66bd03e805c7539 upstream.
    
    Without the patch the kernel generates the following error.
    
     ata11.15: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
     ata11.15: Port Multiplier vendor mismatch '0x197b' != '0x123'
     ata11.15: PMP revalidation failed (errno=-19)
     ata11.15: failed to recover PMP after 5 tries, giving up
    
    This patch helps to bypass this error and the device becomes
    functional.
    
    Signed-off-by: Denis V. Lunev <den@openvz.org>
    Signed-off-by: Tejun Heo <tj@kernel.org>
    Cc: <linux-ide@vger.kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
```

No developers\maintainers have worked on this driver code since.

I'm not going to be able to solve this one for you.

**Comment by Chadster766** [comment]
Why not use USB3.0 since the speeds should similar.

**Comment by jbsky** [comment]
You must patch kernel if you want something work :haha:

http://osdir.com/ml/linux-kernel/2013-11/msg00418.html

**Comment by edwardwong80** [comment]
Thanks for the follow up, so now I understand why it works on my Debian Wheezy since the kernel version is "old enough" to be able to use it. Probably I should give up the crappy JMicron SATA multiplier.

eSATA is more stable compared with USB, but I know this standard wasn't widely adopted elsewhere so the kernel support is limited.

**Comment by Chadster766** [comment]
@jbsky , that patch was include in the kernel prior to 3.12.

**Comment by jbsky** [comment]
I saw kernel already patched, sorry.

**Comment by Chadster766** [comment]
No Problem thanks for the suggestion :smile:
