### ISSUE TITLE
Additional kernel modules (tun, usbserial)

### ISSUE THREAD

**Issue by con7** [Chadster766/McDebian#23]
Hi,

is it possible to compile the next kernel with kernel modules "tun" and "usbserial"? (CONFIG_TUN, CONFIG_USB_SERIAL).
I would need tun module for OpenVPN and usbserial for an external usb modem.

Thanks in advance!

**Comment by Chadster766** [comment]
Do you think I should add all the USB Converter device drivers to? (Ex: CONFIG_USB_SERIAL_GENERIC, CONFIG_USB_SERIAL_SIERRAWIRELESS)

I've almost completed the new beta release for you :smile:

**Comment by con7** [comment]
I think following modules should be enough:

`CONFIG_USB_SERIAL
CONFIG_USB_SERIAL_GENERIC
CONFIG_USB_SERIAL_OPTION`

Cool! I'm looking forward to test it soon 😄 Thanks for your work! It's really awesome to run Debian on the WRT :)

**Comment by Chadster766** [comment]
Ok will do :+1:

**Comment by Chadster766** [comment]
Completed

**Comment by con7** [comment]
Thanks @Chadster766, works great!

**Comment by con7** [comment]
I would need some more modules:

```
CONFIG_USB_NET_RNDIS_HOST
CONFIG_USB_NET_CDCETHER
CONFIG_USB_USBNET
```

But there's no hurry. I already compiled these kernel modules, but it would be nice if you can include it in releases with newer kernels.

**Comment by Chadster766** [comment]
Will do :smile:

**Comment by con7** [comment]
Thanks 😄 👍

**Comment by con7** [comment]
Sorry, forgot one:

`CONFIG_BONDING`

If it's to much, no problem, just tell me. 😃 I can also compile it myself everytime.

**Comment by Chadster766** [comment]
Is no problem :smile:

**Comment by Chadster766** [comment]
@con7 I don't think I can add CONFIG_USB_NET_RNDIS_HOST since it's experimental and proprietary.

**Comment by con7** [comment]
@Chadster766 okay, i didn't consider that. no problem, i'll compile it myself.

**Comment by Chadster766** [comment]
@con7 can you test a new beta for me? 

It has all the request modules added including CONFIG_USB_NET_RNDIS_HOST.

```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V2-FW_VER3_kernel_4_8_15.img
```

```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/rootfs-updates/mcdebian-rootfs-update-v4_8_15-VER3.gz
```

**Comment by con7** [comment]
@Chadster766 i've just tested it and hadn't any problems with your new beta 😃 👍  thanks so much.
