### ISSUE TITLE
vlan tagging on switch ports

### ISSUE THREAD

**Issue by Driver007** [Chadster766/McDebian#25]
hi, is it possible to tag switch ports? my ISP has IPTV and STB shows on vlan6, have no idea how to make to work on debian system.

**Comment by Chadster766** [comment]
Hi @Driver007,

You can do this two ways with McDebian.

1) Implement VLAN in McDebian without the DSA Switch and trunk the VLAN's you want to a managed switch which will breakout the VLAN's to the ports you want to assign them to. (Preferred)

OR

2) Enable the DSA Switch driver and configure VLAN's on the ports. This will drop the WAN to LAN throughput put for any single connection to approx 400-500mbps but 900mbps will still be used across multiple connections.

The easiest is #1 but requires the managed switch.

**Comment by Chadster766** [comment]
You can download the McDebian network base (defaults) configs directly to the (root) 'cd /' of your McDebian router with the below instructions:

 #The standard McDebian config without the DSA Switch activated
```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/base-configs/network-std-config.tar.gz
```

#The standard McDebian config with the DSA Switch activated
```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/base-configs/network-dsa-switch.tar.gz
```

Then extract the either gz file for the base config you want.

 Ex:
```
cd /
tar zxf network-dsa-switch.tar.gz
```

**Comment by Chadster766** [comment]
The Debian vlan package needs to be installed.

```
apt-get install vlan
```

Add 8021q model to load at startup.

```
echo "8021q" >> /etc/modules
```

Add the VLAN subinterfaces to your interfaces file:

```
auto wan.6
iface wan.6 inet static
        vlan-raw-device wan
        address 10.x.x.x
        netmask 255.255.0.0
        network 10.x.0.0
        broadcast 10.x.255.255
        gateway 10.x.x.x
```

**Comment by Chadster766** [comment]
You could instead create bridge interfaces between the WAN VLAN6 and a LAN port:

```
auto br0
        iface br0 inet static
        bridge_ports lan1 lan2 lan3 wlan1 wlan0
        address 192.168.1.1
        netmask 255.255.255.0
        network 192.168.1.0
        broadcast 192.168.1.255

 auto wan.6
 iface wan.6 inet manual
         vlan-raw-device wan

auto br1
iface br1 inet manual
        bridge_ports wan.6 lan4
        address 10.x.x.x
        netmask 255.255.0.0
        network 10.x.0.0
        broadcast 10.x.255.255
        gateway 10.x.x.x
```

**Comment by Chadster766** [comment]
I've discovered that the LAN ports are reversed in the DSA Switch on the WRT1900AC V1. I haven't tested the other models for this yet:

Interface lan1 = phys port4
Interface lan2 = phys port3
Interface lan3 = phys port2
Interface lan4 = phys port1

**Comment by villesinisalo** [comment]
The OpenWRT project lists the port configs for each WRT*AC device [here](https://wiki.openwrt.org/toh/linksys/wrt1x00ac_series#switch_layout)
