### ISSUE TITLE
Wiki: Correct instructions for upgrading from OpenWRT/LEDE

### ISSUE THREAD

**Issue by villesinisalo** [Chadster766/McDebian#26]
Hello,

thanks for this project, looks absolutely awesome. I started installing custom Linux on my WRT1900ACSV2, first with OpenWRT (the LEDE fork to be exact) but soon realised it was not maybe the ideal solution for router this powerful as I ended up doing lots of hacks to make it more Debian-like. Then I discovered your project.

When upgrading from OpenWRT to McDebian I however ran into an issue and nearly bricked my device. The OpenWRT LuCI web interface rejects the WRT1900AC McDebian kernel image, claiming it is corrupt. I ssh'd in and used the OpenWRT tool called [`mtd`](https://wiki.openwrt.org/doc/techref/mtd) to try and force writing the image to the primary kernel bank with `mtd write McDebian-WRT1900AC-V2-FW_VER1_kernel_4.9.12.img /dev/mtd4`, because I was assuming the OpenWRT `mtd` tool would be analogous to the mtd-utils tools [used for flashing a new image once already under McDebian](https://github.com/Chadster766/McDebian/wiki/2.-Firmware-Uploading#flashing-firmware-from-mcdebian). After booting however the device was still running OpenWRT but had booted it from the alternative/backup kernel bank at mtd6. **So flashing McDebian kernel with OpenWRT's `mtd` does not seem to work, and would seem to brick the device if you flash both banks.**

The correct way to flash the McDebian image on OpenWRT is to use  `sysupgrade -n -v -F McDebian-WRT{Model}-FW_VER1_kernel_{Version}.img`. The -F switch forces flashing the image (or it will give the same complaint about corrupt image as the web interface).

I would make a PR for adding this [here to the wiki](https://github.com/Chadster766/McDebian/wiki/2.-Firmware-Uploading#linksys-openwrt-and-dd-wrt-webui-method), but apparently GitHub does not support making PRs against the wiki (?!).

**Comment by Chadster766** [comment]
I've given you collaborator status to McDebian.

Feel free to add yourself to the Design Team on the Wiki home page.

**Comment by villesinisalo** [comment]
@Chadster766 Hello, I got your message two weeks ago. Terribly sorry for my slow reaction, there was the Easter week between during which I was AFK, and on weekdays my resources for OSS are generally quite limited. I viewed your invitation now but it seems to have expired.

**Comment by Chadster766** [comment]
No problem :smile: 

I've resent the invite.

**Comment by villesinisalo** [comment]
Thanks, it's fixed now,

**Comment by Chadster766** [comment]
Thanks :smiley: 

I removed collaborator status unit next time.
