### ISSUE TITLE
[Discussion] Is it safe to run apt-get dist-upgrade on McDebian?

### ISSUE THREAD

**Issue by sid8tive** [Chadster766/McDebian#28]
I assume it is safe to run apt-get update and apt-get upgrade. But what about dist-upgrade? Is that safe? (Asking since I don't want to upgrade the kernel by mistake and brick the device)

**Comment by Chadster766** [comment]
No I don't recommend apt-upgrade or dist-upgrade but I do recommend apt-get update and uninstalling newer versions of packages you area concerned about. 


McDebian's kennel is 4.9.x which is only used in the newer Stretch Debian release which in my opinion is to new to be stable.

**Comment by sid8tive** [comment]
Thanks @Chadster766 !

**Comment by sid8tive** [comment]
PS: For the sake of experimentation, I (after backing up, of course), was able to do a apt-get upgrade (will never risk dist-upgrade, for now) successfully! I know that this is a YMMV thing, and can break the build if one is not careful in ensuring which specific packages get updated.

**Comment by Chadster766** [comment]
Thanks for testing that out.

I it would be great if you could post results of the upgrade after using it for a week or so.

**Comment by sid8tive** [comment]
Yep. I'll post my system uptime and any performance (issues) 1 week from now or so.
