### ISSUE TITLE
[Discussion] Web GUIs

### ISSUE THREAD

**Issue by sid8tive** [Chadster766/McDebian#29]
So, are there any recommended web GUIs we could use on McDebian? I use Webmin on my Ubuntu-based DIY NAS box. Some on the internet have recommended FreedomBox/Plinth. Are there any others out there?

**Comment by ValCher1961** [comment]
Try Ajenti -http://ajenti.org/
There's also an interesting package netdata-Real-time monitoring -https://github.com/firehol/netdata/

**Comment by sid8tive** [comment]
Got it. Will give those a shot. Thank you, @ValCher1961 !
