### ISSUE TITLE
[Discussion] Building McDebian

### ISSUE THREAD

**Issue by sid8tive** [Chadster766/McDebian#30]
Hi @Chadster766 

I wish to build McDebian from source. What packages do I need on my PC for the build environment (beyond build-essential)?  The reason behind doing this is my need to stay bleeding edge: keeping McDebian on the WRT1900ACv1 aligned to Debian mainline with latest package updates, etc (including keeping up with the latest kernel). I wish to do weekly builds. I can also help contribute back into McDebian.

I did see your build notes, but I couldn't interpret them enough to do a step by step reproduction at my end. Your help would be truly appreciated!

[edit] I also want to try building Ubuntu. I've reached out to cilix-lab for that.

Sid

**Comment by jbsky** [comment]
Hi, I have made script to help compiling. 
https://raw.githubusercontent.com/jbsky/Debian-On-WRT1900AC-V1/master/kernel/mkKNLWRT1900AC
Change only the .config file to the root directory.
Maybe @Chadster766 can help provide an updated .config if you like.

**Comment by sid8tive** [comment]
Sweet. Thank you, @jbsky ! I will give this a spin. @Chadster766 , how do I generate the .config?

**Comment by jbsky** [comment]
This script automatically downloads my .config and applies fixes specifically for the V1. After studying the process of creating the firmware through this script, you can try the .config Chadster.

**Comment by sid8tive** [comment]
Got it. I will do that. Thank you, @jbsky

**Comment by Chadster766** [comment]
Thanks @jbsky for providing more info to @sid8tive

**Comment by sid8tive** [comment]
@jbsky Your script worked flawlessly. I just finished building kernel 4.11.9 and the rootfs using debian stretch. need to now test it. Somehow I wasn't able to build 4.12.3 due to a gpio function error during compile time.
