### ISSUE TITLE
Main radios individually configurable for 2.4ghz or 5Ghz

### ISSUE THREAD

**Issue by JosephAllen** [Chadster766/McDebian#39]
It looks like you are disabling bands: https://github.com/Chadster766/McDebian/blob/9396c9c00b22c2456fc378931854e917a8884a0d/linux-4.9.26/drivers/mwlwifi/core.c#L206

Would enabling the bands have an adverse impact on performance?

It sure would be nice to not have a crippled AC model, when each radio is capable of simultaneous broadcasting on both 2.4 and 5Ghz (in theory).

At the very least it would be nice to be able to have the option of 2 radios broadcasting at 5GHz.

**Comment by Chadster766** [comment]
How would a user individually set the radios to 2.4Ghz or 5Ghz in this case?

**Comment by JosephAllen** [comment]
Do it with a Config file. In an ideal world both bands would be on all the time for both radios. Then the network Interface would choose which band to use.

At the very least I'd like to have the ability to use 5Ghz on both radios, one for main use and the 2nd for backhaul.

I'd kill for a router with just two 5Ghz radios, with minor support on the 2.4Ghz band for legacy clients, like a printer.

**Comment by JosephAllen** [comment]
II wonder if there is really and need to select the Band a all if both are using the same SSID. A wireless card can downgrade as necessary to talk to an older wifi Router. Couldn't the wifi card on the router do the same?

If that is true, what's lost in having 2.4 engaged all the time, knowing that the router is capable of talking in both bands simultaneously to support the client. Maybe we are used to having the hardware vendors tell us what's possible so they can sell more stuff? This car will only go 40, to go faster, you'll need two. :-)

**Comment by Chadster766** [comment]
I think the radios can only broadcast on one frequency or the other.

I've offend wondered if it was possible too.

The "iw" command might work to set the radio to one frequency or the other but I don't think that feature is enabled in the driver.

Another option would be to add a USB3.0 wireless adapter with a supported driver for the backhaul. It might be easier and better.

**Comment by JosephAllen** [comment]
How about allowing 2.4 or 5 for each radio. Then adding a cheap 2.4 dongle when both radios are use for 5.

Seems like that would be the most cost effective solution.

Maybe you we can work on Kolaz to allow both bands to be used at once.

Sure it'll require two sets of band settings for each radio, but much better than buying a new router.

That is the magic bullet.

On Sep 7, 2017, at 10:13 PM, Chad McCue <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the radios can only broadcast on one frequency or the other.

I've offend wondered if it was possible too.

The "iw" command might work to set the radio to one frequency or the other but I don't think that feature is enabled in the driver.

Another option would be to add a USB3.0 wireless adapter with a supported driver for the backhaul. It might be easier and better.

**Comment by Chadster766** [comment]
To have both radios 5Ghz a simple change needs to be made in the DTS firmware file for the specific WRT.

I successfully tested this only on the new McDebian 4.9.61 system :boom:

**Comment by Chadster766** [comment]
I've done more testing.

I don't know why but the radio that normally runs 2Ghz when running 5Ghz has a significant drop in signal strength.

Same settings on both radios tested individually:
 
- Normal 5Ghz radio: -45dbm
- Normal 2Ghz radio set to 5Ghz: -82dbm

**Comment by ValCher1961** [comment]
That's what it should be, because the aligned elements that connect the radio to the antenna are different in each module.

**Comment by Chadster766** [comment]
Hi @ValCher1961 

Can that be changed?

**Comment by ValCher1961** [comment]
No, you need to change the items on your router board.

**Comment by Chadster766** [comment]
Thanks @ValCher1961
