### ISSUE TITLE
Enable CONFIG_IP_PIMSM_V1 and CONFIG_IP_PIMSM_V2

### ISSUE THREAD

**Issue by villesinisalo** [Chadster766/McDebian#42]
Multicast routing with e.g. [smcroute](https://github.com/troglobit/smcroute) requires defining `CONFIG_IP_PIMSM_V1=y`
and `CONFIG_IP_PIMSM_V2=y` in the kernel. This would be a good addition; I can't currently get my Smart-TV Chromecast (in LAN) to talk to my phone (in WLAN) because I can't add multicast routes to my WRT that joins the two networks.

It is enabled for amd64 on Debian mainline at least with 3.0.0: http://kernel.alioth.debian.org/config/3.0.0-5/config_amd64_none_amd64

**Comment by Chadster766** [comment]
Thank you for this suggestion. I though I had what was needed for multicast already in place. 

The next McDebian beta release will have:

```
CONFIG_IP_PIMSM_V1=y
CONFIG_IP_PIMSM_V2=y
CONFIG_IPV6_PIMSM_V2=y
```

I'm planning to release the beta today.

**Comment by villesinisalo** [comment]
Thank you! I will try it out and report back.

**Comment by Chadster766** [comment]
Sorry there will be a bit of a delay on this beta. I accidentally copied over my new IPv6 base work that was to be included in the next beta and will have to recreate it before the new beta release.

**Comment by Chadster766** [comment]
The beta release is ready for testing:
https://github.com/Chadster766/McDebian/issues/43
