### ISSUE TITLE
Please move *.bin's from non-HTTPS protechs-online.com to GitHub for HTTPS

### ISSUE THREAD

**Issue by JW0914** [Chadster766/McDebian#48]
Your bootloader recovery bins for the WRT AC Series reside on a non-secure site, opening the possibility for a user to unwittingly be the victim of a MITM attack. Please move them to GitHub, especially since they're bootloader recovery bins.

**Comment by Chadster766** [comment]
Thank you I've updated the TFTP link in the wiki page.

**Comment by JW0914** [comment]
Much appreciated =]  Thank you :)
