### ISSUE TITLE
Wiki page about sensors3.conf need some change

### ISSUE THREAD

**Issue by zhangyoufu** [Chadster766/McDebian#49]
The lm-sensor configuration file on wiki page [Thermal-Protection](https://github.com/Chadster766/McDebian/wiki/B.-Thermal-Protection) need some change. It seems that the `bus` line is required for newer lm-sensors nowadays.

Here's an updated example:
```
bus "i2c-0" "mv64xxx_i2c adapter"
chip "tmp421-i2c-0-4c"
	label temp1 "DDR"
	label temp2 "Wi-Fi"

bus virtual
chip "armada_thermal-virtual-0"
	label temp1 "CPU"
```

**Comment by Chadster766** [comment]
Thanks for the info and I will look into it

**Comment by Chadster766** [comment]
This doesn't seem to work on the WRT3200ACM
