### ISSUE TITLE
wan to br0 and docker question

### ISSUE THREAD

**Issue by Mikei386** [Chadster766/McDebian#52]
First of all thank you so much for your work here.
It's making things quite easy.

Since I want to use my 1200AC as a switch and docker on it, I would like to know if it's possible to add the wan port to the brige (switch port 1-4). In DD-WRT it was possible to use the wan port like a 5th switch port.

Also I tried to install an docker container wich worked but it won't create a network bridge since it can't connect to the br0. Not quite sure whats that about. Maybe you have some ideas already?

Thanks a lot.

**Comment by Chadster766** [comment]
I tested an AP mode with the McDebian beta.

https://github.com/Chadster766/McDebian/issues/50#issuecomment-449871142

**Comment by Mikei386** [comment]
Thanks a lot. It's working now.
One thing I spotted with the beta release is that now my CPU temperature isn't showing anymore.
(WRT1200AC v2)

`root@MCDEBIAN:/# sensors`
`tmp421-i2c-0-4c`
`Adapter: mv64xxx_i2c adapter`
`DDR:          +39.8°C ` 
`WIFI:         +41.8°C  `

As far as docker concerns, I red some posts which suggests it might be a problem with the way the kernel is configured.
Since the message `failed to create endpoint <name> on network bridge` appears is coming from the kernel.
So I guess no luck there.

**Comment by Chadster766** [comment]
Thanks for the feed back,

I'm not sure what happened to the sensors cpu temp.

**Comment by nicolaerosia** [comment]
@Mikei386 in the end, did you manage to use docker ?

**Comment by Mikei386** [comment]
Sadly no. I instead switched to OpenWRT and installed OpenWRT-LXC. So I now have LCX Containers with Debian inside running on OpenWRT. Works like charm.

**Comment by nicolaerosia** [comment]
@Mikei386 Thanks! You're running vanilla OpenWRT and use LXC? Did you have to build your own kernel?

**Comment by Mikei386** [comment]
I build my own version of OpenWRT since there are many components (such as wireless lan or pppoe) which I removed and then selected the LXC components.
