### ISSUE TITLE
hdd boot image

### ISSUE THREAD

**Issue by Lovator** [Chadster766/McDebian#53]
Using a TTL-UART cable, I can set the boot priority from the hard disk.

> setenv nandboot 'scsi init;ext4load scsi 0:1 $defaultLoadAddr kernel;bootm $defaultLoadAddr'
setenv altnandboot 'scsi init;ext4load scsi 0:1 $defaultLoadAddr kernel;bootm $defaultLoadAddr' saveenv

Is it possible to run McDebian from a hard disk without delete partitions  mtd4-mtd7 on nand memory ?

**Comment by Chadster766** [comment]
Yes if you have TTL access to the WRT. I think its as easy as setting the u-boot envar for recovery to 0. This disables the boot count.

**Comment by Lovator** [comment]
Yes i have a TTL.
Please tell me how to write McDebian to hard drive ?

**Comment by Lovator** [comment]
I want to experiment a bit with mcdebian, and I don’t want to touch the firmware is on nand.
I connected the hard drive, McDebian booted, disconnected the hard drive, the stock firmware booted.

**Comment by Chadster766** [comment]
Are you good to go then?

**Comment by Chadster766** [comment]
McDebian supports the WRT1200. The wiki has the details you are looking for.

**Comment by Lovator** [comment]
I just need to burn the mcdebian-stretch-router-WRT-1900-1200-3200-32x-Kernel_4_19_12-base.gz image to my hard drive and connect it to the router and McDebian-Stretch-WRT1200AC-V1-FW_VER1_kernel_4.19.12.img does not need to be written to nand ?

**Comment by Chadster766** [comment]
Yes the kernel is in the firmware which uses the rootfs on the drive.

**Comment by Lovator** [comment]
link is not available  http://www.protechs-online.com/downloads/McDebian/rootfs/mcdebian-stretch-router-wrt-1900-1200-3200-32x-Kernel_4_19_12-base.gz  I can not download file

**Comment by Chadster766** [comment]
Are you using wget?

**Comment by Chadster766** [comment]
Thanks i will look into right away.

**Comment by Lovator** [comment]
Yes, but also tried through the browser with the login and password

**Comment by Chadster766** [comment]
I can't believe I had another typo in the URL. Please try again :confused:

**Comment by Chadster766** [comment]
http://www.protechs-online.com/downloads/McDebian/rootfs/mcdebian-stretch-router-wrt-1900-1200-3200-32x-kernel_4_19_12-base.gz

**Comment by Lovator** [comment]
thanks link earned !!!
