### ISSUE TITLE
Temperature cannot be read

### ISSUE THREAD

**Issue by de-conf** [Chadster766/McDebian#55]
When I run `sensor-detect `
I get it
```
tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
DDR:          +49.6 C  
WIFI:         +51.6 C  
```
no cpu temperature,i search it,found it
https://patchwork.kernel.org/patch/10696619/
but
```
cat /sys/devices/virtual/thermal/thermal_zone*/temp
63691
```
please help me!

**Comment by de-conf** [comment]
In addition, there are a few suggestions:
1. https://github.com/Chion82/netfilter-full-cone-nat
This is a fullconenat project, I hope you can add it to the kernel support.
2. The intranet address of ipv6 should avoid using the beginning of fc. This address will cause the browser to not use ipv6, even if it can ping to the ipv6 address in the terminal.

**Comment by Chadster766** [comment]
> When I run `sensor-detect `
> I get it
> 
> ```
> tmp421-i2c-0-4c
> Adapter: mv64xxx_i2c adapter
> DDR:          +49.6 C  
> WIFI:         +51.6 C  
> ```
> 
> no cpu temperature,i search it,found it
> https://patchwork.kernel.org/patch/10696619/
> but
> 
> ```
> cat /sys/devices/virtual/thermal/thermal_zone*/temp
> 63691
> ```
> 
> please help me!

Thanks but that patch was added to the kernel in 2018 and sensors-detect still doesn't find it.

**Comment by de-conf** [comment]
> > When I run `sensor-detect `
> > I get it
> > ```
> > tmp421-i2c-0-4c
> > Adapter: mv64xxx_i2c adapter
> > DDR:          +49.6 C  
> > WIFI:         +51.6 C  
> > ```
> > 
> > 
> > no cpu temperature,i search it,found it
> > https://patchwork.kernel.org/patch/10696619/
> > but
> > ```
> > cat /sys/devices/virtual/thermal/thermal_zone*/temp
> > 63691
> > ```
> > 
> > 
> > please help me!
> 
> Thanks but that patch was added to the kernel in 2018 and sensors-detect still doesn't find it.

What should I do?  Before the openwrt ' lm-sensor ' can detect the CPU temperature

**Comment by Chadster766** [comment]
Using your command line will provide the temperature.

For the WRT1900AC V1 the McDebian default fancontrol is configured and working.

**Comment by de-conf** [comment]
My machine is WRT 1900 AC V2,Command line can not detect CPU temperature, Can not use thermal protection，I will try to use the source to build ` lm-sensor `, hope to be valid.I'm afraid of overheating temperatures lead to machine scrapped

**Comment by Chadster766** [comment]
> My machine is WRT 1900 AC V2,Command line can not detect CPU temperature, Can not use thermal protection，I will try to use the source to build `lm-sensor`, hope to be valid.I'm afraid of overheating temperatures lead to machine scrapped

Isn't the below the CPU temperature of 63C?
```
cat /sys/devices/virtual/thermal/thermal_zone*/temp
63691
```

In the McDebian wiki I have an example of a custom script you could use for thermal protection on the WRT1900AC V2:
https://github.com/Chadster766/McDebian/wiki/B.-Thermal-Protection#debian-thermal-protection

**Comment by Chadster766** [comment]
> In addition, there are a few suggestions:
> 
> 1. https://github.com/Chion82/netfilter-full-cone-nat
>    This is a fullconenat project, I hope you can add it to the kernel support.
> 2. The intranet address of ipv6 should avoid using the beginning of fc. This address will cause the browser to not use ipv6, even if it can ping to the ipv6 address in the terminal.

I'm researching this module. It's an interesting concept.

**Comment by de-conf** [comment]
> > In addition, there are a few suggestions:
> > 
> > 1. https://github.com/Chion82/netfilter-full-cone-nat
> >    This is a fullconenat project, I hope you can add it to the kernel support.
> > 2. The intranet address of ipv6 should avoid using the beginning of fc. This address will cause the browser to not use ipv6, even if it can ping to the ipv6 address in the terminal.
> 
> I'm researching this module. It's an interesting concept.

So will this module be added to the kernel?

**Comment by de-conf** [comment]
In addition, I upgraded the debian version to buster, and now the sensors are back to normal. I think I am more suitable for the radical distribution. In my free time, I will try to build the ` armarch `  according to your article. I hope I can give me some time....
```
sensors
mv88e6xxx002-mdio-2
Adapter: MDIO adapter
temp1:        +54.0 C  (crit = +100.0 C)

mv88e6xxx000-mdio-0
Adapter: MDIO adapter
temp1:        +54.0 C  (crit = +100.0 C)

tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
temp1:        +48.8 C  
temp2:        +50.6 C  

mv88e6xxx003-mdio-3
Adapter: MDIO adapter
temp1:        +54.0 C  (crit = +100.0 C)

mv88e6xxx001-mdio-1
Adapter: MDIO adapter
temp1:        +54.0 C  (crit = +100.0 C)

f10e4078.thermal-virtual-0
Adapter: Virtual device
temp1:        +63.2 C  

mv88e6xxx004-mdio-4
Adapter: MDIO adapter
temp1:        +54.0 C  (crit = +100.0 C)
```

**Comment by Chadster766** [comment]
Thanks this is good information.

**Comment by Chadster766** [comment]
The full cone nat project is a module so not built into the kernel.

You could build the module and install it in your router now if you wanted.

**Comment by de-conf** [comment]
When I upgrade Debain, restarted and can not enter the system ，it not give me a address，sad！

**Comment by Chadster766** [comment]
> When I upgrade Debain, restarted and can not enter the system ，it not give me a address，sad！

You will have to create a new McDebian rootfs on the usbkey.
