### ISSUE TITLE
hdd boot image

### ISSUE THREAD

**Issue by de-conf** [Chadster766/McDebian#56]
A good news！I have almost succeeded in porting arm-archlinux!
But I met a problem, because archlinux is scrolling the release of the release, the kernel upgrade is very frequent, can I start the system on the U disk directly, do not use Nand Flash? I see another problem in issue，but Use the commands that use to provide the machine can not start the machine！
If it may be possible to provide a method

**Comment by Chadster766** [comment]
> But I met a problem, because archlinux is scrolling the release of the release, the kernel upgrade is very frequent, can I start the system on the U disk directly, do not use Nand Flash? 

This would be possible. It would require making an initramfs and a kernel for it. These would be one time loaded into nand. The initramfs would load the new kernel for U drive and remount the root file system to the U drive. Not the easiest thing to accomplish.

**Comment by de-conf** [comment]
Do you mean it?
Boot sequence：
uboot（nand）--->initramfs（nand）---->kernel（udisk）--->rootfs（udisk）
