### ISSUE TITLE
Uboot problem

### ISSUE THREAD

**Issue by de-conf** [Chadster766/McDebian#57]
I am very sorry for disturbing you! ! But I am now very interested in this! !
I want to start usb-storge directly from uboot！
But I saw what you wrote before.
` USB3 works but not for the rootfs boot drive due to a u-boot limitation. Once the kernel is up the USB3 driver is loaded. `  [it's here ](https://github.com/ValCher1961/McDebian_WRT3200ACM/issues/5)
I found that the u-boot of the wrt ac series is done by you! 
### I want to know the details about how to build the u-boot
And can  solve this bug?
Why am I obsessed with starting the kernel of usb?
When the kernel is above the flash, the kernel after startup is still flash, My operation can't affect the kernel.I don't know what to do
Looking forward to your reply!

**Comment by ValCher1961** [comment]
Excuse me, I'll answer. Maybe this will help you, instead of USB3 use the SATA/USB2 port, it is supported from U-Boot.

**Comment by de-conf** [comment]
> Excuse me, I'll answer. Maybe this will help you, instead of USB3 use the SATA/USB2 port, it is supported from U-Boot.

Glad to your answer, do you mean uboot support for booting rootfs from usb 2.0?

**Comment by de-conf** [comment]
> Excuse me, I'll answer. Maybe this will help you, instead of USB3 use the SATA/USB2 port, it is supported from U-Boot.

Sorry, ask again how to start rootfs using the uboot command? Do I need to change uboot env var? What is it?
I tried the following command and the result could not be started.
```
Setenv nandboot 'scsi init;ext4load scsi 0:1 $defaultLoadAddr kernel;bootm $defaultLoadAddr'
Setenv altnandboot 'scsi init;ext4load scsi 0:1 $defaultLoadAddr kernel;bootm $defaultLoadAddr' saveenv
```

**Comment by ValCher1961** [comment]
Yes, take a look - https://github.com/ValCher1961/McDebian_WRT3200ACM/wiki/%23-Using-external-drives-in-U-Boot

**Comment by de-conf** [comment]
> Yes, take a look - https://github.com/ValCher1961/McDebian_WRT3200ACM/wiki/%23-Using-external-drives-in-U-Boot

Thank you for this great work, I will experiment with him right away! Thank you very much for your answer! !

**Comment by ValCher1961** [comment]
Ok!

**Comment by de-conf** [comment]
> Ok!

Take the liberty to ask, can you explain the uboot build steps? I am very interested! I have downloaded eldk

**Comment by ValCher1961** [comment]
Sorry, no, I was not able to collect U-Boot :(

**Comment by de-conf** [comment]
> Sorry, no, I was not able to collect U-Boot :(

It's ok, anyway.
Thank you for your help! !

**Comment by ValCher1961** [comment]
A small remark, format the disk with the command - mkfs -t ext4  -O ^64bit -L kernel /dev/sda1, because U-Boot does not work with 64bit.

**Comment by de-conf** [comment]
> A small remark, format the disk with the command - `mkfs -t ext4 -O ^64bit -L kernel /dev/sda1`, because U-Boot does not work with 64bit.

Ok, thanks for your reminder, I am watching your wiki

**Comment by de-conf** [comment]
> A small remark, format the disk with the command - `mkfs -t ext4 -O ^64bit -L kernel /dev/sda1`, because U-Boot does not work with 64bit.

I noticed that your kernel is specific, can I use the  official kernel?

**Comment by ValCher1961** [comment]
Linksys and OPENWRT cannot be used only from Chadster or similar ones that download Linux from disk.

**Comment by de-conf** [comment]
> Linksys and OPENWRT cannot be used only from Chadster or similar ones that download Linux from disk.

Not quite understand! 
In addition, I have a problem, uboot can not read usb part
details as following:
```
Marvell>> usb info 
1: Hub,  USB Revision 2.0
 - u-boot EHCI Host Controller 
 - Class: Hub
 - PacketSize: 64  Configurations: 1
 - Vendor: 0x0000  Product 0x0000 Version 1.0
   Configuration: 1
   - Interfaces: 1 Self Powered 0mA
     Interface: 0
     - Alternate Setting 0, Endpoints: 1
     - Class Hub
     - Endpoint 1 In Interrupt MaxPacket 8 Interval 255ms

Marvell>> usb part

no USB devices available
```

**Comment by ValCher1961** [comment]
I apologize for the inaccuracy of the interpreter.
You wrote - 
> ... can I use the official kernel?

You cannot use the OEM core Linksys and OpenWRT.
You can use the kernel from Chadster. 

> I have a problem, uboot can not read usb part
details as following:

Try to rerun the - `usb reset` command. After it is executed, do you have Storage Device in the line?
```
scanning bus 0 for devices... 2 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
```

**Comment by de-conf** [comment]
> I apologize for the inaccuracy of the interpreter.
> You wrote -
> 
> > ... can I use the official kernel?
> 
> You cannot use the OEM core Linksys and OpenWRT.
> You can use the kernel from Chadster.
> 
> > I have a problem, uboot can not read usb part
> > details as following:
> 
> Try to rerun the - `usb reset` command. After it is executed, do you have Storage Device in the line?
> 
> ```
> scanning bus 0 for devices... 2 USB Device(s) found
>        scanning usb for storage devices... 1 Storage Device(s) found
> ```
It doesn't matter, no need to apologize,
Yes,I run ` usb reset `  ` usb start` have  a Storage Device，As you wrote！
```
scanning bus 0 for devices... 2 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
```
but run ` usb part ` 
` no USB devices available `
Also, my uboot source is 
http://www.protechs-online.com/downloads/McDebian/u-boot-recovery/WRT1900ACv2_WRT1900ACS_uboot_v1.0.13.bin
my rootfs choose is 
https://archlinuxarm.org/platforms/armv7/marvell/clearfog

**Comment by ValCher1961** [comment]
You have formatted USB storage, recorded in its root kernel and rootfs, but you do not read the disc?
We can assume only one thing is that there is some incompatibility of USB flash with the port eSata/USB2. Try using a different USB storage.

**Comment by de-conf** [comment]
> You have formatted USB storage, recorded in its root kernel and rootfs, but you do not read the disc?
> We can assume only one thing is that there is some incompatibility of USB flash with the port eSata/USB2. Try using a different USB storage.

yes，I tried, I used USB Flash and USB HDD, respectively, but the problem is the above display, USB HDD on USB2.0 port using `USB RESET 'will hold 
```
scanning bus 0 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 
```
I suspect that the lead is caused by the lack of power supply
USB HDD on USB3.0 can use `usb reset` but `usb part ` no display information
usb flash use `usb reset ` no display also.
I not have estat wire and I buy a one tomorrow.

**Comment by ValCher1961** [comment]
I sometimes, for tests, use USB-HDD or USB-SSD 2.5" drives, and I have no problem with the power.
I use the eSATA cord with the SSD drive.
