### ISSUE TITLE
Missing Kernel features

### ISSUE THREAD

**Issue by Redferne** [Chadster766/McDebian#59]
Trying to play around with Wireguard network namespaces and FireQOS and found out that it's not possible. CONFIG_NET_NS and CONFIG_IFB are not enabled. Please enable those in your next build. 

I can rebuild the kernel myself (with some assistance). Are there any additional patches required for WRT3200ACM? Or can I just take the vanilla 4.9.12 tree? How about the mwl firmware drivers? Thanks!

**Comment by Chadster766** [comment]
You don't need any 3rd party software to configure Wireguard.

It's been a long time since I configure a Wireguard. If I remember correctly you create and interface for it in /etc/network/interfaces and you are good to go.

**Comment by Redferne** [comment]
Sure. But I would like to do split tunnel and application based VPN routing. And thus in need for network namespaces. See here: https://www.wireguard.com/netns/

Just tell me if I need anything else to build my own kernel other than your base .config and the base kernel source?

Thanks!

**Comment by Chadster766** [comment]
That was a good read thanks. 

I can add those configs to my next release.

IMO Wireguard doesn't have many advantages over OpenVPN since it's so complex to configure which confuses me because I thought Wireguard's premise was to make it easy to configure.

It's been a while but if I remember correctly you will need my DTS, mwlwifi and Wireguard files\modules to build the kernel and modules needed for the WRT. They should be in this github.

**Comment by Redferne** [comment]
I was hoping to get better throughput with Wireguard, openvpn caps out @ 12mbit/s here with cpu @ 100% load.

I can see your dts but mwl and wireguard is missing in the 4.9.12 directory?

**Comment by Chadster766** [comment]
I will see if I can get that up loaded for this weekend.

**Comment by Redferne** [comment]
Long weekend? 😉

**Comment by Chadster766** [comment]
Sorry for the delay I ended up having to do some traveling.

I've added the kernel configs you wanted, updated the modules and updated the kernel to 4.19.74.

I have a Buster rootfs which I'm testing now.

**Comment by Chadster766** [comment]
The newest Wireguard source code can be copied into the kernel source code. It will properly compile without modification.

**Comment by Redferne** [comment]
Ah! Great. Will you push 4.19.74 here?

**Comment by Chadster766** [comment]
Yes with buster rootfs

**Comment by Chadster766** [comment]
Hi @Redferne,

https://github.com/Chadster766/McDebian/issues/62
