### ISSUE TITLE
Boot problems linksys wrt3200 Flashing firmware from McDebian

### ISSUE THREAD

**Issue by himetfile** [Chadster766/McDebian#60]
Hi sorry for disturbing read your guide Flashing firmware from McDebian
i did following on linksys wrt 3200

`flash_erase /dev/mtd5 0 0`
`flash_erase /dev/mtd6 0 0`
`flash_erase /dev/mtd7 0 0`
`flash_erase /dev/mtd8 0 0`
`nandwrite -p /dev/mtd5 McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img`
`nandwrite -p /dev/mtd7 McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img`

it will not boot up was wondering if i done it right Regards

**Comment by Chadster766** [comment]
Yes it looks right. 

Did you create your rootfs usb key?

**Comment by himetfile** [comment]
yes i did it continues to blink the power led and usb seems to be in standby mode

**Comment by Chadster766** [comment]
Do you have the usb key plugged into the USB2.0 port?

**Comment by himetfile** [comment]
Yes tried both usb and e-sata and redid usb drive

**Comment by himetfile** [comment]
any ideas could i maybe fix it without  using TTL cable

**Comment by Chadster766** [comment]
Did you have McDebian previously on the WRT?

**Comment by himetfile** [comment]
No previously was running openwrt

**Comment by himetfile** [comment]
Sorry i meant to write linksys firmware path it then did boot from usb device

**Comment by Chadster766** [comment]
Looks like you didn't follow the McDebian firmware upload instructions for OpenWRT.

Were did you run those command in your original post?

**Comment by himetfile** [comment]
First i used linksys to patch firmware then created usb stick after i booted it up it worked great them followed Flashing firmware from McDebian instructions

**Comment by Chadster766** [comment]
Oh so you flashed McDebian from the Linksys firmware and it booted fine with the usb key?

**Comment by himetfile** [comment]
yes true

**Comment by Chadster766** [comment]
It now doesn't boot with the same usb key in the same usb plug?

**Comment by himetfile** [comment]
yes correct

**Comment by Chadster766** [comment]
Then your flash_erase command were successful but your nandwrite commands failed. This is critical to notice that the nandwrite commands failed because you could have troubleshooted that. Once you reboot then the only way to recover is via USB to TTL.

**Comment by himetfile** [comment]
Thank you very mutch mate
