### ISSUE TITLE
WRT3200ACM not booting after nandwrite

### ISSUE THREAD

**Issue by ItzBrandoN** [Chadster766/McDebian#61]
DD-WRT webUI upgrade to mcdebian. Did reflash per the mcdebian flash instructions and everything looked fine to me before reboot.  It showed writing data to block x at offset xxxxxxx. I got that from block 0 to 37 for both partitions. After a reboot two LAN lights are on and the power light is flashing. Anything you can suggest other than TTL?

**Comment by ItzBrandoN** [comment]
root@MCDEBIAN:/# wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img
--2019-09-23 22:35:24--  http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img
Resolving www.protechs-online.com (www.protechs-online.com)... 63.247.71.18
Connecting to www.protechs-online.com (www.protechs-online.com)|63.247.71.18|:80... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm="McDebian Firmwares"
Reusing existing connection to www.protechs-online.com:80.
HTTP request sent, awaiting response... 200 OK
Length: 4877185 (4.7M) [application/octet-stream]
Saving to: 'McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img'

McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19. 100%[================================================================================================================>]   4.65M  23.1MB/s    in 0.2s

2019-09-23 22:35:25 (23.1 MB/s) - 'McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img' saved [4877185/4877185]

root@MCDEBIAN:/# flash_erase /dev/mtd5 0 0
Erasing 128 Kibyte @ 300000064 -- 4784360 % complete mplete
root@MCDEBIAN:/# flash_erase /dev/mtd6 0 0
Erasing 128 Kibyte @ 300000064 -- 4497640 % complete mplete
root@MCDEBIAN:/# flash_erase /dev/mtd7 0 0
Erasing 128 Kibyte @ 300000064 -- 4632808 % complete mplete
root@MCDEBIAN:/# flash_erase /dev/mtd8 0 0
Erasing 128 Kibyte @ 300000064 -- 4751592 % complete mplete
root@MCDEBIAN:/# nandwrite -p /dev/mtd5 McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img
Writing data to block 0 at offset 0x0
Writing data to block 1 at offset 0x20000
Writing data to block 2 at offset 0x40000
Writing data to block 3 at offset 0x60000
Writing data to block 4 at offset 0x80000
Writing data to block 5 at offset 0xa0000
Writing data to block 6 at offset 0xc0000
Writing data to block 7 at offset 0xe0000
Writing data to block 8 at offset 0x100000
Writing data to block 9 at offset 0x120000
Writing data to block 10 at offset 0x140000
Writing data to block 11 at offset 0x160000
Writing data to block 12 at offset 0x180000
Writing data to block 13 at offset 0x1a0000
Writing data to block 14 at offset 0x1c0000
Writing data to block 15 at offset 0x1e0000
Writing data to block 16 at offset 0x200000
Writing data to block 17 at offset 0x220000
Writing data to block 18 at offset 0x240000
Writing data to block 19 at offset 0x260000
Writing data to block 20 at offset 0x280000
Writing data to block 21 at offset 0x2a0000
Writing data to block 22 at offset 0x2c0000
Writing data to block 23 at offset 0x2e0000
Writing data to block 24 at offset 0x300000
Writing data to block 25 at offset 0x320000
Writing data to block 26 at offset 0x340000
Writing data to block 27 at offset 0x360000
Writing data to block 28 at offset 0x380000
Writing data to block 29 at offset 0x3a0000
Writing data to block 30 at offset 0x3c0000
Writing data to block 31 at offset 0x3e0000
Writing data to block 32 at offset 0x400000
Writing data to block 33 at offset 0x420000
Writing data to block 34 at offset 0x440000
Writing data to block 35 at offset 0x460000
Writing data to block 36 at offset 0x480000
Writing data to block 37 at offset 0x4a0000
root@MCDEBIAN:/# nandwrite -p /dev/mtd7 McDebian-Stretch-WRT3200ACM-V1-FW_VER1_kernel_4.19.12.img
Writing data to block 0 at offset 0x0
Writing data to block 1 at offset 0x20000
Writing data to block 2 at offset 0x40000
Writing data to block 3 at offset 0x60000
Writing data to block 4 at offset 0x80000
Writing data to block 5 at offset 0xa0000
Writing data to block 6 at offset 0xc0000
Writing data to block 7 at offset 0xe0000
Writing data to block 8 at offset 0x100000
Writing data to block 9 at offset 0x120000
Writing data to block 10 at offset 0x140000
Writing data to block 11 at offset 0x160000
Writing data to block 12 at offset 0x180000
Writing data to block 13 at offset 0x1a0000
Writing data to block 14 at offset 0x1c0000
Writing data to block 15 at offset 0x1e0000
Writing data to block 16 at offset 0x200000
Writing data to block 17 at offset 0x220000
Writing data to block 18 at offset 0x240000
Writing data to block 19 at offset 0x260000
Writing data to block 20 at offset 0x280000
Writing data to block 21 at offset 0x2a0000
Writing data to block 22 at offset 0x2c0000
Writing data to block 23 at offset 0x2e0000
Writing data to block 24 at offset 0x300000
Writing data to block 25 at offset 0x320000
Writing data to block 26 at offset 0x340000
Writing data to block 27 at offset 0x360000
Writing data to block 28 at offset 0x380000
Writing data to block 29 at offset 0x3a0000
Writing data to block 30 at offset 0x3c0000
Writing data to block 31 at offset 0x3e0000
Writing data to block 32 at offset 0x400000
Writing data to block 33 at offset 0x420000
Writing data to block 34 at offset 0x440000
Writing data to block 35 at offset 0x460000
Writing data to block 36 at offset 0x480000
Writing data to block 37 at offset 0x4a0000

**Comment by Chadster766** [comment]
Do you have the USB rootfs plugged into the USB2.0 port?

**Comment by ItzBrandoN** [comment]
Wow.... you know what, I’ve had it plugged into the USB 3.0 port the entire time. I didn’t even notice there was a combo port. I did just plug it into the 2.0 though and it still isn’t booting. I think my next step is going to be a Sandisk flash drive.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ItzBrandoN** [comment]
Just an update. Created the rootfs on a sandisk but still not booting. I have a usb to TTL coming in tomorrow and I should have some success with that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Chadster766** [comment]
Great, please let me know if something is wrong with my instructions.

**Comment by ItzBrandoN** [comment]
Ok, so after the reset I’m getting Cannot open root device “sda1” or unknown-block(8,1): error -6
I will be doing some googling in the meantime to see if I can self resolve.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Chadster766** [comment]
To reproduce the issue load linksys firmware then load McDebian for the linksys firmware and then the follow the final step of McDebian reload to both partitons.

**Comment by ItzBrandoN** [comment]
I reformatted the sandisk and loaded the file system back on it and everything is running smooth. Sorry for wasting your time!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Chadster766** [comment]
No problem and good job
