### ISSUE TITLE
Building the kernel as a .deb package

### ISSUE THREAD

**Issue by villesinisalo** [Chadster766/McDebian#64]
Upgrading and customizing a McDebian system would be much easier if the kernel was distributed as a .deb file. For upgrades, the kernel .deb file could even be distributed from a private apt-get repository (PPA). This way, users would ever need to install the base system once and from there on upgrading would be as simple as using `apt-get update && apt-get upgrade`, like on any Debian system. This is how e.g. Raspbian (Raspberry PI Debian distribution) works. They have a deb package called `raspberrypi-kernel`.

As an minimal solution, the custom kernel could depend on `mtd-utils` and contain an install script that flashes the kernel to correct bank(s) on each router model.

AFAIK there should be no reason why this was *not* possible, and I'd be interested into looking to making it to work. However, for that there would need up-to-date build instructions for the current kernel. Am I not wrong in assuming that [these instructions](https://www.snbforums.com/threads/linksys-wrt1900ac-wrt1900acs-wrt1200ac-and-wrt3200acm-router-debian-implementation.28394/) from 2015 are probably not very not up to date? ;)

Having up-to-date instructions for building the kernel (as a deb or not) would of course enable users to customize the kernel config to their own needs more easily, as lots of the issues users seem to be facing are related to the kernel config options.

**Comment by Chadster766** [comment]
I have fine tuned the process somewhat from that article.

If you can provide instructions on how to create the deb file to install a McDebian kernel that would really speed things up.

I think fw_setenv, flash_erase and nandwrite commands would have to be run from the kernel upgrad\update deb installation process.

**Comment by Chadster766** [comment]
Sorry I doubt I will have time to work on this recommendation.
