### ISSUE TITLE
2.4 wifi worked half-a-day after setup, now no longer working

### ISSUE THREAD

**Issue by bmalnersic** [Chadster766/McDebian#68]
Hi,

Just yesterday I setup McDebian on WRT1900ACS V2 and literally had no issues. Everything was working perfectly, including 2.4 GHz wifi. 
However few hours ago, I ran into issues with 2.4 GHz (5 GHz works fine all the time). 
First I would not list in Windows/Android device, then after killing hostapd processes and running _hostapd -d /etc/hostapd/wlp2so.conf_ with various option changes, no luck connecting. 
I see a lot of messages like:
`nl80211: Drv Event 60 (NL80211_CMD_FRAME_TX_STATUS) received for wlp2s0
nl80211: Frame TX status event
wlp2s0: Event TX_STATUS (16) received
nl80211: BSS Event 59 (NL80211_CMD_FRAME) received for wlp2s0
nl80211: RX frame da=ff:ff:ff:ff:ff:ff sa=38:78:62:8f:e3:92 bssid=ff:ff:ff:ff:ff:ff freq=2437 ssi_signal=-23 fc=0x40 seq_ctrl=0x1f60 stype=4 (WLAN_FC_STYPE_PROBE_REQ) len=100
Ignore Probe Request due to DS Params mismatch: chan=6 != ds.chan=4
nl80211: BSS Event 59 (NL80211_CMD_FRAME) received for wlp2s0
nl80211: RX frame da=ff:ff:ff:ff:ff:ff sa=38:78:62:8f:e3:92 bssid=ff:ff:ff:ff:ff:ff freq=2437 ssi_signal=-30 fc=0x40 seq_ctrl=0x1f70 stype=4 (WLAN_FC_STYPE_PROBE_REQ) len=100
Ignore Probe Request due to DS Params mismatch: chan=6 != ds.chan=8
`
And after few attempts, wifi network will get disabled. I tried replacing my current config with default from your base image (only changing country code, I live in Slovenia), same issue.

Do you have any good pointers on what could be causing the issue. I don't see anything really sticking out in dmesg or hostapd debug output, except that Ignore Probe Request, but checking the Internet that does not seem to be real issue.

Just wanted to ask before digging deeper. Maybe you saw something like that in the past?

Strange thing is, it was really working perfect for ~10 hrs.

Kind regards,

      Blaz

**Comment by Chadster766** [comment]
Did you change the country code?

**Comment by bmalnersic** [comment]
Yes, first thing I did after "install". And then it worked fine for ~8 hours and then all of a sudden issue appeared. Rebooting, restarting hostapd, changing config does not help. 5Ghz works b.p.

**Comment by bmalnersic** [comment]
One thing I should probably change - time zone, ntp time sync and such.

**Comment by Chadster766** [comment]
I recommend first test with McDebian defaults wireless and don't change country code for testing.

**Comment by Chadster766** [comment]
Just change default ssid.

**Comment by bmalnersic** [comment]
Turns out the issue was (probably, it works now for half-a-day b.p.) the country_code setting in hostapd config file(s). I have changed the value (as written in initial message) to match my country ISO (SI) code. And 2.4GHz and 5GHz worked initially and then after ~10 hrs issues with 2.4GHz began. Interestingly 2.4GHz SSID would appear and I would be able to connect after ~12 hrs, but then again it failed when trying to connect multiple times.

At the end, I found this [Crash after Country Code change](https://github.com/kaloz/mwlwifi/issues/355) and after changing country_code value to FR (from SI, Slovenia) and few hostapd restarts, now it all seems to work fine.

Appreciate your quick replays and for making McDebian. Before WRT1900ACS v2 I was using Cisco E4200v2 with Debian for like 8 years and well, it is simply great!

**Comment by bmalnersic** [comment]
Probably was the right word; after some time, 2.4GHz SSID is no longer being broadcasted. hostapd_cli   interface wlp2s0 works, status is OK and ENABLED, reload is OK, level DEBUG shows only few Event TX_MGMT (18) received per seconds.
Nothing in dmesg or journal -b | grep wlp2s0.... At this point I am thinking:

- run hostapd with only 2.4GHz with dd, logging to file
- test router with Linksys FW or OpenWRT and see if issue also occurs there.

There are no issues with 5GHz.
