### ISSUE TITLE
DHCPv6 or 6in4

### ISSUE THREAD

**Issue by Armik2** [Chadster766/McDebian#72]
Hi. Something i'm completely confused with ipv6. Now i get ipv6 settings from the provider via dhcp and i get an with subnet :: 1/128 but do not share per subnet, share only if change to net.ipv6.conf.wan.accept_ra = 1 net.ipv6.conf.all.forwarding = 0, but when I restart again I get only one address. It would also be interesting find out the settings for 6in4. Thanks

**Comment by Chadster766** [comment]
McDebian is preconfigure for IPv6 NAT as described in the below wiki article:

https://github.com/Chadster766/McDebian/wiki/5.-Network-Configuration

I like this configuration because you can easily firewall, forward and locate local LAN IPv6 resources.

**Comment by Armik2** [comment]
How to set up bypassing NAT? ipv6 does not work for me with your configuration. I added dhcp 1 and request_prefix 1 to the inet6 interface and it seems to work. He began to receive an address and a prefix but today it stopped working.

**Comment by Chadster766** [comment]
Sure McDebian can be configure however you like.

**Comment by Armik2** [comment]
del
