### ISSUE TITLE
default loading uboot WRT1200AC

### ISSUE THREAD

**Issue by Lovator** [Chadster766/McDebian#76]
good afternoon, tell me how to return to the standard boot from Nand memory, I installed the boot from hdd.
Now I want to switch back to openwrt or native firmware.

Setenv nandboot 'scsi init;ext4load scsi 0:1 $defaultLoadAddr kernel;bootm $defaultLoadAddr'
Setenv altnandboot 'scsi init;ext4load scsi 0:1 $defaultLoadAddr kernel;bootm $defaultLoadAddr' 
saveenv

I understand correctly that I need to enter the following commands to boot from nand ?

setenv nandboot 'setenv bootargs console=ttyS0,115200 root=/dev/mtdblock5 ro rootdelay=1 rootfstype=jffs2 earlyprintk $mtdparts;nand read $defaultLoadAddr $priKernAddr $priKernSize; bootm $defaultLoadAddr'
setenv altnandboot 'setenv bootargs console=ttyS0,115200 root=/dev/mtdblock7 ro rootdelay=1 rootfstype=jffs2 earlyprintk $mtdparts;nand read $defaultLoadAddr $altKernAddr $altKernSize; bootm $defaultLoadAddr'
saveenv

**Comment by ValCher1961** [comment]
Hi!
Yes, it is possible as you write, but in order not to make a mistake in typing a long command line, execute a short command -
`Marvell>> resetenv`
https://github.com/ValCher1961/McDebian_WRT3200ACM/wiki/%23-Using-external-drives-in-U-Boot
