### ISSUE TITLE
kernel > 4.4.0

### ISSUE THREAD

**Issue by jbsky** [Chadster766/McDebian#8]
Do wait the next longtime release is a good choice but no before september. The next LTS number is 4.8.

**Comment by ValCher1961** [comment]
Until September, we will polish the existing one.

**Comment by jbsky** [comment]
@Chadster about https://github.com/Chadster766/McDebian/issues/5 issue, I read this can be fixed by setting /proc/sys/vm/min_free_kbytes to 16384.

**Comment by ValCher1961** [comment]
@jbsky 
Swap file or swap disk help?

**Comment by jbsky** [comment]
No swap, this helps to avoid a crash of kernel. Do a samba test to confirm is needed.

**Comment by Chadster766** [comment]
Will setting the min_free_kbytes to 16384 remove the need for the smbd cgroup memory usage limit?

**Comment by jbsky** [comment]
Normally yes.

**Comment by jbsky** [comment]
Normally yes

**Comment by Chadster766** [comment]
Finally Kernel 4.7 is released. I've been waiting for this one. Unfortunate no new Long Term has been release but that's ok.

I'm excited about kernel 4.7 for this application because of all the switch driver and DTS updates included in this version.

**Comment by ValCher1961** [comment]
@all
There is a problem.
In a home network installed NAS Synology connected on Lan 1Gb to wrt1900.
On the NAS installed Samba and share the directory with files Video. When playing on a laptop with WiFi on the NAS, when using Windows Media Player movies go smoothly. If you use VLC video goes in spurts.
I have the same old router WRT350v2, which set McDebian (kernel 4.1.21), WiFi Atheroc. Network configuration settings identical WRT1900. If it is connected instead wrt1900, and use VLC, the video goes smoothly.
Hostapd settings I have are the same as in kaloz/mwlwifi.
In what may be a problem in the driver for the Marvell 88W8864?

**Comment by ValCher1961** [comment]
@Chadster766 
The good news, will build a new kernel.

**Comment by Chadster766** [comment]
I've complete a new Beta release of McDebian firmware with kernel 4.7.0 and a new full root file system

http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1200AC-V1-FW_VER1_kernel_4_7_0.img
http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V1-FW_VER1_kernel_4_7_0.img
http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V2-FW_VER1_kernel_4_7_0.img

http://www.protechs-online.com/downloads/McDebian/rootfs/mcdebian-router-WRT-1900-1200-Kernel_4_7_0-base.gz

## Website access:
Username: "mcdebian"
Password: "mcdebian123

### I've been impressed with the new kernel and mwlwifi driver. It's performing quite well.
