### ISSUE TITLE
Kernel 4.7.X

### ISSUE THREAD

**Issue by ValCher1961** [Chadster766/McDebian#9]
@Chadster766
I put your kernel on my file system, but things did not go as I expected. I think we have a very big difference.
Now I will try to put your file system and check it out.

**Comment by ValCher1961** [comment]
Yes, all is well passed, the magazine is clean.
How to understand that you do not install the buffer-manager.
By the way, I had this same warning as you
```
[    2.717138] of: dev_pm_opp_of_cpumask_add_table: couldn't find opp table for cpu:0, -19
[    2.725204] cpu cpu1: opp_list_debug_create_link: Failed to create link
[    2.731869] cpu cpu1: _add_opp_dev: Failed to register opp debugfs (-12)
```
How to get rid of it?

**Comment by Chadster766** [comment]
@ValCher1961 thanks for pointing out the BM issue. I knew it was built into the 4.7.0 kernel but I forgot to activate it in the kernel build .config.

I'm going to activate and test BM now.

**Comment by ValCher1961** [comment]
Well, wait.

**Comment by Chadster766** [comment]
I've completed my testing and found an issue. Kernels 4.6 - 4.7 while the systems are very stable the mvneta Ethernet driver's IRQ will only use one CPU even though it's smp_affinity is set to use both CPU's (value 3). This cause the WAN to LAN throughtput to be cut in half. It's not a problem for me because I don't have an Internet connection close to 400mbps but for those that have +400mbps it's a problem.

**Comment by ValCher1961** [comment]
@Chadster766 
Unexpectedly, timely noticed.
Here is an article about the problem, read this help?
I installed irqbalance and the picture has changed, that's how it was
```
root@wrt1900ac:~# cat /proc/interrupts
           CPU0       CPU1
 16:   28367660   24103691      MPIC   5 Level     armada_370_xp_per_cpu_tick
 19:      93069          0      MPIC  31 Level     mv64xxx_i2c
 20:       1117          0      MPIC  41 Level     serial
 26:          0          0      MPIC  45 Level     ehci_hcd:usb1
 27:   19303387       2482      MPIC   8 Level     mvneta
 29:     101549          0      MPIC  55 Level     sata_mv[f10a0000.sata]
 30:         31          0      MPIC 113 Level     f10d0000.nand
 31:          0          0      MPIC  48 Level     f1090000.crypto
 32:          0          0      MPIC  49 Level     f1090000.crypto
 72:          0          0  f1018140.gpio   0 Edge      WPS
 73:          0          0  f1018140.gpio   1 Edge      Factory Reset Button
 89:          0          0      MPIC  58 Level     xhci-hcd:usb2
 90:  325287398          0      MPIC  59 Level     mwlwifi
 91:  313354384          0      MPIC  60 Level     mwlwifi
 92:          2          0      MPIC  51 Level     f1060900.xor
 93:          2          0      MPIC  94 Level     f10f0900.xor
IPI0:          0          0  CPU wakeup interrupts
IPI1:          0          0  Timer broadcast interrupts
IPI2:     400067    1883233  Rescheduling interrupts
IPI3:        208        150  Function call interrupts
IPI4:          0          0  CPU stop interrupts
IPI5:          0          0  IRQ work interrupts
IPI6:          0          0  completion interrupts
Err:          0
```
and became
```
root@wrt1900ac:~# cat /proc/interrupts
           CPU0       CPU1
 16:     165655     103031      MPIC   5 Level     armada_370_xp_per_cpu_tick
 19:        476          0      MPIC  31 Level     mv64xxx_i2c
 20:       1258          0      MPIC  41 Level     serial
 26:          0          0      MPIC  45 Level     ehci_hcd:usb1
 27:     121598       2693      MPIC   8 Level     mvneta
 29:       5871          0      MPIC  55 Level     sata_mv[f10a0000.sata]
 30:         31          0      MPIC 113 Level     f10d0000.nand
 31:          0          0      MPIC  48 Level     f1090000.crypto
 32:          0          0      MPIC  49 Level     f1090000.crypto
 72:          0          0  f1018140.gpio   0 Edge      WPS
 73:          0          0  f1018140.gpio   1 Edge      Factory Reset Button
 89:          0          0      MPIC  58 Level     xhci-hcd:usb2
 90:    1554683      62433      MPIC  59 Level     mwlwifi
 91:      61282    1505440      MPIC  60 Level     mwlwifi
 92:          2          0      MPIC  51 Level     f1060900.xor
 93:          2          0      MPIC  94 Level     f10f0900.xor
IPI0:          0          0  CPU wakeup interrupts
IPI1:          0          0  Timer broadcast interrupts
IPI2:       5591      36073  Rescheduling interrupts
IPI3:         23         52  Function call interrupts
IPI4:          0          0  CPU stop interrupts
IPI5:          0          0  IRQ work interrupts
IPI6:          0          0  completion interrupts
Err:          0
```

**Comment by Chadster766** [comment]
No change in mvneta irq, it only uses cpu0 but about 1 percent hit cpu0.

**Comment by ValCher1961** [comment]
You have in the kernel is installed?
It can affect?
```
 CONFIG_SCHED_SMT:

Improves the CPU scheduler's decision making when dealing with
MultiThreading at a cost of slightly increased overhead in some
places. If unsure say N here.

Symbol: SCHED_SMT [=n]
Type  : boolean
Prompt: SMT scheduler support
Location:
     -> Kernel Features
       -> Symmetric Multi-Processing (SMP [=y])
         -> Support cpu topology definition (ARM_CPU_TOPOLOGY [=y])
Defined at arch/arm/Kconfig:1313
Depends on: ARM_CPU_TOPOLOGY [=y]
```

**Comment by ValCher1961** [comment]
Oh, irqbalance hung router.
I remove it.

**Comment by Chadster766** [comment]
Good one I will test SCHED_SMT kernel option.

**Comment by ValCher1961** [comment]
I also build the kernel with this option.

**Comment by ValCher1961** [comment]
Enabling this option does not give effect.
I am waiting for you to confirm.

**Comment by Chadster766** [comment]
I think it's has to do with all the new marvell mvneta driver code to do with cpu affinity. It seem that the newer Linux kernels have taken the policy of letting the driver choose affinity but in this case the code is broken.

**Comment by ValCher1961** [comment]
Last attempt.
There is option Allow booting SMP kernel on uniprocessor systems SMP_ON_UP [=у], included by default.
Whether this option перенапралять all interruptions on cpu0 can?

**Comment by Chadster766** [comment]
How did SMP_ON_UP work out?

**Comment by ValCher1961** [comment]
All to no avail (

**Comment by Chadster766** [comment]
Thanks for trying. Did you do any throughput testing with kernel 4.7?

**Comment by ValCher1961** [comment]
I have no way to test WAN <-> LAN. I can run tests within the LAN.
The results will tell.

**Comment by Chadster766** [comment]
LAN throughputs are good. I have multiple WRT's so I can do WAN to LAN testing without taking down my primary network.

If you have a giga bit internet connection then a www.speedtest.net would work well to.

**Comment by ValCher1961** [comment]
Unfortunately my provider gives only 100 MB

**Comment by ValCher1961** [comment]
I do not give rest to the problem of IRQ distribution, found the information.
http://free-electrons.com/blog/linux-4-6-released-with-free-electrons-contributions/
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=cb49d86dbe7a3277fb329c30206d4d95470c879c

**Comment by Chadster766** [comment]
Yes it looks like the code isn't working well all be it very stable connection.

I've seem many other kernel commits since then for mvneta smp affinity.

**Comment by Chadster766** [comment]
See the two mvneta interrupts on 27 and 28. See how 99% are on CPU0 and there smp_affinity is 3. What’s really odd is the mwlwifi interrupts 90 and 91 are set for different CPU’s but CPU0 and CPU1 are being used as if smp_affinity was 3 for both.

```
root@MCDEBIAN:~# cat /proc/interrupts
           CPU0       CPU1
 16:      39994      34135      MPIC   5 Level     armada_370_xp_per_cpu_tick
 19:          0          0      MPIC  31 Level     mv64xxx_i2c
 20:       5387          0      MPIC  41 Level     serial
 26:          0          0      MPIC  45 Level     ehci_hcd:usb1
 27:       5751          1      MPIC   8 Level     mvneta
 28:      44556         25      MPIC  10 Level     mvneta
 29:          0          0      MPIC  55 Level     sata_mv[f10a0000.sata]
 30:       6078          0      MPIC 113 Level     f10d0000.nand
 31:          0          0      MPIC  48 Level     f1090000.crypto
 32:          0          0      MPIC  49 Level     f1090000.crypto
 72:          0          0  f1018140.gpio   0 Edge      WPS
 73:          0          0  f1018140.gpio   1 Edge      Factory Reset Button
 90:     612244     119075      MPIC  59 Level     mwlwifi
 91:     206644     537633      MPIC  60 Level     mwlwifi
 92:          2          0      MPIC  51 Level     f1060900.xor
 93:          2          0      MPIC  94 Level     f10f0900.xor
 94:       5156          0  MPIC MSI 524288 Edge      xhci_hcd
IPI0:          0          0  CPU wakeup interrupts
IPI1:          0          0  Timer broadcast interrupts
IPI2:       1574       8486  Rescheduling interrupts
IPI3:        438        507  Function call interrupts
IPI4:          0          0  CPU stop interrupts
IPI5:          0          0  IRQ work interrupts
IPI6:          0          0  completion interrupts
Err:          0
root@MCDEBIAN:~# cat /proc/irq/27/smp_affinity
3
root@MCDEBIAN:~# cat /proc/irq/28/smp_affinity
3
root@MCDEBIAN:~# cat /proc/irq/90/smp_affinity
1
root@MCDEBIAN:~# cat /proc/irq/91/smp_affinity
2
root@MCDEBIAN:~#
```

**Comment by ValCher1961** [comment]
I find only one explanation.
If the notice comes CPU interrupt, the kernel simply offers the account cpu (0), cpu (1) ... cpu (N). With such a proposal in 100% will be processed in interrupt cpu (0), and only when the cpu (0) will be employed, and the current interrupt processing comes new interrupt request, it turns cpu (1).

**Comment by Chadster766** [comment]
That's probably true but regardless Kernel 4.7 works but only half throughput.

I just finished building McDebian for kernel 4.4.16 and it's got full gigabit throughput! I will make a beta available in a few minutes

**Comment by ValCher1961** [comment]
Ok!

**Comment by Chadster766** [comment]
With kernel 4.4.16 I managed to test mvneta driver throughput and it was good. Then I tested mwlwifi and got a `Internal error: Oops: 17 [#1] SMP ARM` at `mwl_mac80211_ampdu_action`.

How I got mwlwifi to compile on 4.4.2 was add:

```
--- a/include/net/mac80211.h
+++ b/include/net/mac80211.h
@@ -2740,6 +2740,33 @@ enum ieee80211_reconfig_type {
 };

 /**
+ * struct ieee80211_ampdu_params - AMPDU action parameters
+ *
+ * @action: the ampdu action, value from %ieee80211_ampdu_mlme_action.
+ * @sta: peer of this AMPDU session
+ * @tid: tid of the BA session
+ * @ssn: start sequence number of the session. TX/RX_STOP can pass 0. When
+ *      action is set to %IEEE80211_AMPDU_RX_START the driver passes back the
+ *      actual ssn value used to start the session and writes the value here.
+ * @buf_size: reorder buffer size  (number of subframes). Valid only when the
+ *      action is set to %IEEE80211_AMPDU_RX_START or
+ *      %IEEE80211_AMPDU_TX_OPERATIONAL
+ * @amsdu: indicates the peer's ability to receive A-MSDU within A-MPDU.
+ *      valid when the action is set to %IEEE80211_AMPDU_TX_OPERATIONAL
+ * @timeout: BA session timeout. Valid only when the action is set to
+ *      %IEEE80211_AMPDU_RX_START
+ */
+struct ieee80211_ampdu_params {
+        enum ieee80211_ampdu_mlme_action action;
+        struct ieee80211_sta *sta;
+        u16 tid;
+        u16 ssn;
+        u8 buf_size;
+        bool amsdu;
+        u16 timeout;
+};
+
+/**
```

**Comment by Chadster766** [comment]
Now I'm excited! :smiley: 

The below mwlwifi version at this commit is fully compatible with Kernel 4.4.16

```
commit af93c39bdce22b3bd1a12e6fb2a1097f9a448ecf
Author: David Lin <dlin@marvell.com>
Date:   Wed Jun 1 15:19:02 2016 +0800

    Removed code related to MFG.

    Signed-off-by: David Lin <dlin@marvell.com>
```

5Ghz wireless speed tests are as fast as I've ever seen!

```
C:\Users\chad\Downloads\iperf-3.0.11-win32>iperf3 -c 192.168.200.3
Connecting to host 192.168.200.3, port 5201
[  4] local 192.168.1.102 port 12891 connected to 192.168.200.3 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  15.0 MBytes   126 Mbits/sec
[  4]   1.00-2.00   sec  16.6 MBytes   139 Mbits/sec
[  4]   2.00-3.00   sec  17.7 MBytes   149 Mbits/sec
[  4]   3.00-4.00   sec  18.5 MBytes   155 Mbits/sec
[  4]   4.00-5.00   sec  17.4 MBytes   146 Mbits/sec
[  4]   5.00-6.00   sec  17.8 MBytes   149 Mbits/sec
[  4]   6.00-7.00   sec  17.6 MBytes   147 Mbits/sec
[  4]   7.00-8.00   sec  17.9 MBytes   150 Mbits/sec
[  4]   8.00-9.00   sec  17.7 MBytes   149 Mbits/sec
[  4]   9.00-10.00  sec  17.6 MBytes   148 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec   174 MBytes   146 Mbits/sec                  sender
[  4]   0.00-10.00  sec   174 MBytes   146 Mbits/sec                  receiver

iperf Done.

C:\Users\chad\Downloads\iperf-3.0.11-win32>iperf3 -c 192.168.200.3 -R
Connecting to host 192.168.200.3, port 5201
Reverse mode, remote host 192.168.200.3 is sending
[  4] local 192.168.1.102 port 12893 connected to 192.168.200.3 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  13.2 MBytes   110 Mbits/sec
[  4]   1.00-2.00   sec  17.4 MBytes   146 Mbits/sec
[  4]   2.00-3.00   sec  17.2 MBytes   144 Mbits/sec
[  4]   3.00-4.00   sec  17.8 MBytes   149 Mbits/sec
[  4]   4.00-5.00   sec  17.9 MBytes   150 Mbits/sec
[  4]   5.00-6.00   sec  17.7 MBytes   148 Mbits/sec
[  4]   6.00-7.00   sec  17.7 MBytes   149 Mbits/sec
[  4]   7.00-8.00   sec  17.4 MBytes   146 Mbits/sec
[  4]   8.00-9.00   sec  17.9 MBytes   150 Mbits/sec
[  4]   9.00-10.00  sec  17.8 MBytes   150 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   172 MBytes   144 Mbits/sec    2             sender
[  4]   0.00-10.00  sec   172 MBytes   144 Mbits/sec                  receiver

iperf Done.

C:\Users\chad\Downloads\iperf-3.0.11-win32>
```

Sorry I have to leave but I should be able to put out a beta tonight :smile:

**Comment by jbsky** [comment]
With ath9k, 2,4GHz, 300Mbits/, in 2 stream MIMO, I can reach 20MBytes / (160Mbits/) and more. 144Mbit is poor perf... 
Theoricly, we can achieve 866Mbits with 90 % of loss, but with this driver....

**Comment by Chadster766** [comment]
@jbsky that's great. Please post iPerf3 testing results like I did for the ath9k driver. This will make sure we are comparing apples to apples :smile:

**Comment by Chadster766** [comment]
I've completed a new Beta release of McDebian firmware with kernel 4.4.16 and a new full root file system

http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1200AC-V1-FW_VER1_kernel_4_4_16.img
http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V1-FW_VER1_kernel_4_4_16.img
http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V2-FW_VER1_kernel_4_4_16.img

http://www.protechs-online.com/downloads/McDebian/rootfs/mcdebian-router-WRT-1900-1200-Kernel_4_4_16-base.gz

Website access:

Username: "mcdebian"
Password: "mcdebian123"

**Comment by jbsky** [comment]
Well, I will give a shot this afternoon.

**Comment by jbsky** [comment]
Rootfs problem :
1- Probleme with udev, the script which write rules doesnt work correctly with V1, I have disabled this services.
2- DSA switch not work.
`[   10.112070] Distributed Switch Architecture driver version 0.1`
`[   10.118006] mvneta f1070000.ethernet eth0: [0]: could not detect attached switch`
`[   10.125458] mvneta f1070000.ethernet eth0: [0]: couldn't create dsa switch instance (error -22)`
Kernel problem : 
`[    6.562470] EXT4-fs (sda1): couldn't mount as ext3 due to feature incompatibilities`
`[    6.621555] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)`
declare in .config

**Comment by ValCher1961** [comment]
@jbsky
DSA in the kernel 4.7.0 you do not work?

**Comment by jbsky** [comment]
no, chadster's work, so 4.4.16, rootfs+firmware

**Comment by ValCher1961** [comment]
understandably.

**Comment by Chadster766** [comment]
@jbsky I've implement DSA in 4.4.16 but not loading the switch driver module at startup in the base rootfs because it's only useful if you really need port vlan support. The module is there and can be added to /etc/modules but then some network\firewall\dhcpd\iptables.up.rules config files will need to be changed as well. 

mv88e6xxx_drv

For ISP VLAN application requirements I would not load the switch module for performance purposes and instead VLAN Trunk WAN to LAN and have a managed switch do the VLAN isolation.

**Comment by Chadster766** [comment]
@jbsky the udev-network-interface-rules.service script should work I've tested it a few times with both WRT1900AC V1 and V2

**Comment by jbsky** [comment]
[Log.txt](https://github.com/Chadster766/McDebian/files/404042/Log.txt)
Check log after fresh install of your work.

**Comment by Chadster766** [comment]
@jbsky please post output of the below command:

cat /etc/systemd/udev-network-interface-rules

**Comment by jbsky** [comment]
[70-persistent-net.rules.txt](https://github.com/Chadster766/McDebian/files/404115/70-persistent-net.rules.txt)
[udev-network-interface-rules.txt](https://github.com/Chadster766/McDebian/files/404116/udev-network-interface-rules.txt)

**Comment by Chadster766** [comment]
@jbsky and the output of the below commands:

strings /dev/mtd3 | grep -w modelNumber
strings /dev/mtd3 | grep -w hw_revision

**Comment by jbsky** [comment]
root@MCDEBIAN:~# strings /dev/mtd3 | grep -w modelNumber
modelNumber=WRT1900AC-EU
root@MCDEBIAN:~#  strings /dev/mtd3 | grep -w hw_revision
hw_revision=1

**Comment by Chadster766** [comment]
In /etc/systemd/udev-network-interface-rules change:

if  strings /dev/mtd3 | grep -w 'modelNumber=WRT1900AC'

To:

if  strings /dev/mtd3 | grep -w 'modelNumber=WRT1900AC-EU'

See if that straightens it out :smile:

**Comment by jbsky** [comment]
It work!

**Comment by Chadster766** [comment]
@jbsky thanks, I will fix this and include it in the published release of McDebian 4.4.16

**Comment by jbsky** [comment]
Please fixe /proc/sys/vm/min_free_kbytes to 16384.

**Comment by jbsky** [comment]
Thank

**Comment by Chadster766** [comment]
@jbsky are you certain /proc/sys/vm/min_free_kbytes is necessary with this rootfs? If you are I will add it for sure.

**Comment by jbsky** [comment]
Sûr! After a samba test, with default value as 2005, kernel crash.
I test with 2011, kernel survey.

So, U can set to 2011, if you want more security you can up to 16386.
Can you post your .config, and all patch?

**Comment by jbsky** [comment]
When I say "With ath9k, 2,4GHz, 300Mbits/, in 2 stream MIMO, I can reach 20MBytes / (160Mbits/) and more. 144Mbit is poor perf..."
I make an Hostspot with an other PC with a atheros card and I test with a Window7 client.

**Comment by Chadster766** [comment]
@jbsky thanks for the clarification on the ath9k testing you were doing :smile:

**Comment by Chadster766** [comment]
I will add vm.min_free_kbytes=16384 sysctl.conf and update the McDebian repo with current kernel 4.4.16 .config and any other changes I've made to the rootfs.

**Comment by Chadster766** [comment]
@jbsky I'm not sure why this worked for you because both "if" statements are true.
```
In /etc/systemd/udev-network-interface-rules change:

if strings /dev/mtd3 | grep -w 'modelNumber=WRT1900AC'

To:

if strings /dev/mtd3 | grep -w 'modelNumber=WRT1900AC-EU'
```

**Comment by Chadster766** [comment]
McDebian rootfs 4.4.16 updated with min_free_kbytes set to 16384

**Comment by jbsky** [comment]
"Maybe it just needed to be rebooted or something"
Right!  But strange, if you want try to understand something, search wlan2 in log.

[capture.wrt1900ac.txt](https://github.com/Chadster766/McDebian/files/405199/capture.wrt1900ac.txt)

**Comment by Chadster766** [comment]
I don't understand how Debian udev reorganizes those devices but when boot is complete the adapters are organized properly :smile:

**Comment by Chadster766** [comment]
The McDebian 4.4.16 kernel .config is updated in the repo now.

McDebian 4.4.16 doesn't have any patch files in use at this time. (Clean unpatched kernel)
